### ISSUE TITLE
Support Patch to a Navigation Property (OData 7.0.0) (title edited)

### ISSUE THREAD

**Issue by egbertn** [OData/WebApi#945] opened 2017-03-20 19:00 UTC
*Short summary (3-5 sentences) describing the issue.*  

### Assemblies affected
OData.Net lib 7.0.*

### Reproduce steps
  public async Task<IHttpActionResult> Patch(Guid key, Delta<company> delta)

Include a collection or complex property in the Json say 
{
    "id": "[guid]"
    "name": "My Company",
    "addresses": [{"address": "siliconroad", "number": 123, "city": "LA", "zipcode": "2134324" }]
}
### Expected result
No ModelState validation errors.
 

### Actual result
ModelState contains errors: "Cannot support complex types" (or something along that line)

### Additional details
This has been fixed for ODataLib 6.15 
but NOT for 7.0
https://github.com/OData/WebApi/issues/135

7.0 is useless without this feature.

**Comment by omric-axonize** [comment] 2017-06-22 13:31
Any fix or workaround available?

**Comment by omric-axonize** [comment] 2017-11-05 13:24
any news on this regression bug?

**Comment by egbertn** [comment] 2017-11-05 20:49
I wrote my own (compatible) patch, because that takes less time than to contribute a pull request to github :(

**Comment by xuzhg** [comment] 2017-11-06 17:44
@egbertn 

1. If **patch** an entity with collection of complex type property, it should work. See test [here](https://github.com/xuzhg/WebApiSample/blob/master/v6.x/WebApi6xFeaturesTest/Complex/ComplexTypeTest.cs)

The url looks like " ~/odata/Customers(1)"

2. If **patch** a collection of complex type property in the entity, it's not supported by design. See the code comments [here](https://github.com/OData/WebApi/blob/master/src/System.Web.OData/OData/Routing/Conventions/PropertyRoutingConvention.cs#L113),  Maybe we did not understand spec correctly. @mikepizzo Would you please help from the spec perspective?

BTW, The url looks like " ~/odata/Customers(1)/Addresses"

**Comment by egbertn** [comment] 2017-11-06 19:20
@xuzhg  please look at https://github.com/OData/WebApi/issues/135
This is the issue, not being able to patch entity types in a collection! :) but the error is that a complex type cannot be patched.

**Comment by xuzhg** [comment] 2017-11-07 00:52
@egbertn Sorry, can you give me an example about "patch entity types in a collection!"?

**Comment by egbertn** [comment] 2017-11-07 09:32
@xuzhg See https://github.com/egbertn/ODataTest

Look into the unit test named PatchMustSucceed

**Comment by xuzhg** [comment] 2017-11-07 18:19
Hi, @egbertn 

OData spec v4.0 doesn't define the behavior to patch an entity with a navigation property or a collection of navigation property. Your service defines the `Address` as entity type, so, the `Addresses` property is treated as collection of navigation property. That's the problem.

![image](https://user-images.githubusercontent.com/9426627/32509896-9e190b06-c3a3-11e7-860b-bc27d970c015.png)

I send out a PR for your repo to change some codes to make the test pass. Please take a look at: https://github.com/egbertn/ODataTest/pull/1

I got some information from @mikepizzo that OData spec v4.0.1 has added the semantics to patch an entity with navigation property.  Maybe @mikepizzo  has more inputs for that "semantics"

**Comment by xuzhg** [comment] 2017-11-08 18:00
For navigation property:

1. You can use "$ref" to update the navigation property.
2. You can wait for the v4.0.1 feature to be implemented in the ODL.

I close this issue and feel free to re-open or file a new issue if you have further concern. 

Thanks!

**Closed by xuzhg** 2017-11-08 18:00 UTC
Labels: P2, regression

**Comment by awaitJosh** [comment] 2018-10-04 18:53
Hi @xuzhg,

just in case, here the same question as in: https://github.com/egbertn/ODataTest/pull/1

If I send a request with nested property to a route like this: /odata/Products(1)/Supplier/$ref I get a 404. If I send a request with nested properties in my JSON Doc the delta is null.

I don´t really understand what to do here to solve the problem. I have a similar setup like this OData/WebApi#992 . I don´t know what I am missing and it would be great if you provide me a little example.

Btw: I´ve found this document: http://odata.github.io/WebApi/#03-02-built-in-routing-conventions
As far as I understood, the spec says, that I have to write multiple patch-actions for each related entity. Is that the way to follow?

Kind regards

**Comment by alexandrevribeiro** [comment] 2019-05-22 17:57
Hi @awaitJosh,

For what it's worth, if in your case it's acceptable having a nested object as *Complex Object* instead of *Navigation Property* check out [this answer](https://github.com/OData/WebApi/issues/964#issuecomment-494902891).
