### ISSUE TITLE
Add related object to a newly created entity with ODataController and DataServiceContext

### ISSUE THREAD

**Issue by tfabian** [OData/WebApi#2071] opened 2019-08-07 13:51 UTC
I would like to save a newly created entity with a newly created child in a single changeset (batch), with Microsoft.OData.Client 7.6.0 and Microsoft.AspNet.OData 7.1.0. The relationship between them is required: [dbo].[BoxInstance].[IdTemplateInstance] (FK, int, not null)
I've tried to call this:
```
var templateInstance = new TemplateInstance();
var boxInstance = new BoxInstance();

dataServiceContext.AddObject("TemplateInstances", templateInstance);
dataServiceContext.AddObject("BoxInstances", boxInstance);
dataServiceContext.AddLink(templateInstance, "BoxInstances", boxInstance);
```

This doesn't work because BoxInstance.IdTemplateInstance is 0 during the post, (ForeignKey violation).
My second attempt was to call AddRelatedObject:

```
dataServiceContext.AddObject("TemplateInstances", templateInstance);
dataServiceContext.AddRelatedObject(templateInstance, "BoxInstances", boxInstance);
dataServiceContext.SaveChangesAsync(SaveChangesOptions.BatchWithSingleChangeset);
```

In this case I receive the following error message:
```_{"error":{"code":"","message":"No HTTP resource was found that matches the request URI 'http://localhost:41256/TemplateInstances(372)/BoxInstances'.","innererror":{"message":"No routing convention was found to select an action for the OData path with template '~/entityset/key/navigation'.","type":"","stacktrace":""}}}_```

I have the following pocos and a ODataController:
```
  public class TemplateInstance : DomainEntity
  {
    public List<BoxInstance> BoxInstances { get; set; }
  }

  public class BoxInstance : DomainEntity
  {
    public TemplateInstance TemplateInstance { get; set; }
    public int IdTemplateInstance { get; set; }
  }

  //server side
  public class TemplateInstancesController : ODataController
  {
    [AcceptVerbs("POST", "PUT")]
    public IHttpActionResult CreateLink([FromODataUri]int key, string navigationProperty, [FromBody]Uri link)
    {
    }

    [AcceptVerbs("POST", "PUT")]
    public IHttpActionResult CreateRef(string navigationProperty, [FromBody] Uri link, ODataQueryOptions<TEntity> queryOptions)
    {
    }
  }
```

This is not a valid solution, because the first step can't be rolled back in case of failure of the second save changes:
```
dataServiceContext.Add(templateInstance);

dataServiceContext.SaveChanges();

boxInstance.IdTemplateInstance = templateInstance.Id;

dataServiceContext.Add(boxInstance);

dataServiceContext.SaveChanges();
```

Thanks!

**Comment by AdamCaviness** [comment] 2020-07-14 21:48
I _believe_ I have also hit this issue with the latest stable versions: 

- Microsoft.AspNetCore.OData 7.4.1
- Microsoft.OData.Core and all 7.6.2

I have been migrating our server from net48 to netcoreapp3.1.  We make use of AddRelatedObject() and this causes batch saves (via BatchWithSingleChangeset) to fail, returning a 404. Since there have been several changes to aspnetcore OData api configuration I made a simple client/server sample to determine if my configuration was at fault. I was surprised I could reproduce this issue in the sample; it doesn't appear to be my Startup configuration. 

This can be reproed with the newer endpoint routing and the older non-endpoint routing. In the attached sample I left both routing approaches but the newer approach is commented out. The newer endpoint routing returns 404 on the **outer** request. The older non-endpoint rounding configuration returns an outer 200 response with the **inner** request marked as 404 Not Found. 

Please check out the sample:
https://github.com/AdamCaviness/ODataCoreAddRelatedObject

Start both projects and choose option 3 in the client to batch save a parent and two child entities. The sample was modified from another sample [found here](https://github.com/OData/WebApi/issues/2029#issuecomment-608174541). Thank you.

**Comment by AdamCaviness** [comment] 2020-07-16 15:18
I have found and fixed the issue I'm hitting. I suppose other AspNetCore.OData consumers have not hit this because calling AddRelatedObject() from the client produces a batch request that isn't natively routed without a custom routing convention. Both of my sample repositories contain a routing convention to address this need. In [my aspnet core sample](https://github.com/AdamCaviness/ODataCoreAddRelatedObject) you can inspect the "fix" branch where I modified `ODataBatchRequestItem` in the following way:


```
string queryString = context.Request.QueryString.HasValue ? context.Request.QueryString.Value : String.Empty;
string resolvedRequestUrl = ContentIdHelpers.ResolveContentId(queryString, contentIdToLocationMapping);
if (!string.IsNullOrEmpty(resolvedRequestUrl))
{
	Uri resolvedUri = new Uri(resolvedRequestUrl, UriKind.RelativeOrAbsolute);
	if (resolvedUri.IsAbsoluteUri)
	{
		context.Request.CopyAbsoluteUrl(resolvedUri);
	}
	else
	{
		context.Request.QueryString = new QueryString(resolvedRequestUrl);
	}
}

context.Request.SetODataContentIdMapping(contentIdToLocationMapping); 
```


became:

```
string displayUrl = context.Request.GetDisplayUrl();
string resolvedRequestUrl = ContentIdHelpers.ResolveContentId(displayUrl, contentIdToLocationMapping);
if (!string.IsNullOrEmpty(resolvedRequestUrl))
{
	Uri resolvedUri = new Uri(resolvedRequestUrl, UriKind.Absolute);
	context.Request.CopyAbsoluteUrl(resolvedUri);
}

context.Request.SetODataContentIdMapping(contentIdToLocationMapping);
```

The crux of the issue is that `ContentIdHelpers.ResolveContentId()` requires the url, not the querystring. It therefore returned an empty string which resulting in never calling `context.Request.CopyAbsoluteUrl()` which prevented the request's path from being updated from the ContentId syntax (like $1) to the expanded uri syntax. You may compare this with [my aspnet framework sample](https://github.com/AdamCaviness/ODataAddRelatedObject) to see what was done in `ODataBatchRequestItem` there. Once I can verify my change with unit tests I'll submit a PR. Thanks for any attention you give this, it's very much appreciated!

**Closed** 2020-09-17 05:26 UTC
Labels: P2, bug

**Comment by rblanca** [comment] 2023-03-11 12:45
Hi guys...using latest version 7.15 on blazor wasm and I'm having troubles with AddRelatedObject...if the parent entity is also a new entity to be added...the url of the request odd....Example

var parentEntity = new ParentEntity { Id ....};
var relatedEntity = new relatedEntity { Id ....};
container.AddToParentEntity(parentEntity);
container.AddRelatedObject(parentEntity, nameof(parentEntity.Relateds), relatedEntity);
await container.SaveChangesAsync();

Insert of the ParentEntity works fine...but not the request for AddRelatedObject. the url that is trying to reach is:

POST http://localhost:7263/OData/Relateds HTTP/1.1

btw "OData" is the default route prefix

when It should be something like this

POST http://localhost:7263/OData/Parent({key})/Relateds

The same happend if you use batch or don't... Or I'm wrong?. Thanks
