### ISSUE TITLE
7.3 on 3.1: Unbound Action ODataActionParameters always null.

### ISSUE THREAD

**Issue by NetTecture** [OData/WebApi#2045] opened 2020-02-06 08:11 UTC
The following action:

        [HttpPost()]
        [ODataRoute("InspectionDuty/Operations.SingleChange")]
        public Task<IActionResult> OperationsSingleChange(ODataActionParameters parameters) {

results in parameters always being a null.

This one works:

        [HttpPost()]
        [ODataRoute("Account({key})/Operations.CanOperate")]
        public IActionResult ActionOperationsCanOperate(Guid key, ODataActionParameters parameters) {

but it is bound (to a specific Account).

https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/odata-actions-and-functions has no example of an unbound action.

This worked - without OdataActionParameters and with [FromBody] in the past. Not having any way to get this working is a regression. And not a good one.

**Comment by NetTecture** [comment] 2020-02-06 08:22
This is something with deserialization. I have rewind enabled for the body, and if I use this code:

            Request.Body.Position = 0;
            using (var reader = new System.IO.StreamReader(Request.Body)) {
                var body = await reader.ReadToEndAsync();
                var p = Newtonsoft.Json.JsonConvert.DeserializeObject<ActionOperationsSingleChangeParameter>(body);
                return await OperationsBulkChange(p2);
...
            }

I see the body and can deserialize it. Something is wrong with deserialization in 3.1

**Comment by xuzhg** [comment] 2020-02-06 18:56
@NetTecture In case I misunderstood. You mentioned "CanOperate" is bound (to a specific Account), Can I assume that  [ODataRoute("InspectionDuty/Operations.SingleChange")] is not bound function?
If that's right, you can't call the unbound function with the namespace? It's weird. Would you please share your metadata?

**Comment by NetTecture** [comment] 2020-02-06 20:28
@xuzhg The metadata is at http://api.obb.tuev-daily.de/odata/$metadata - that is actually part of a public API we maintain.

CanOperate is bound and works. SingleChange is unbound and does not work. It is also an action - the payload is acutally quite complex due to serious logging requirements.

In the bound function, ODataActionParameters is "never" null and contains the data submitted.

In the unbound function it is null.

This code is upgraded from the older version in .NET core 2.2 and there it worked perfectly.

**Comment by ben5Kuda** [comment] 2020-06-03 09:52
I can confirm that this is an issue that i am also experiencing since migrating to .NET Core 3.1. OData unbound actions fail to map correctly and the ODataActionParameters are always null.

**Comment by xuzhg** [comment] 2020-06-03 20:13
@NetTecture 

[This blog](https://devblogs.microsoft.com/odata/tutorial-sample-functions-actions-in-web-api-v2-2-for-odata-v4-0-type-scenario/) illustrates the bound/unbound, action import and function import.

From your metadata, I see the following "SingleChange" action defined, from the attribute "IsBound" equals to "true", it's a bound action.

```xml
<Action Name="SingleChange" IsBound="true">
<Parameter Name="bindingParameter" Type="Collection(PropertyCore.InspectionDuty)"/>
<Parameter Name="Comment" Type="Edm.String" Nullable="false"/>
<Parameter Name="Change" Type="PropertyCore.InspectionDutyChange" Nullable="false"/>
</Action>
```

So, I can't understand you mentioned "SingleChange is unbound and does not work. ".

@NetTecture @ben5Kuda I created a sample to play with bound/unbound action at https://github.com/xuzhg/WebApiSample/tree/master/IssuesOnWebApi/issue2045, it works fine. Please help check is it not same as your project?

**Comment by hemirunner426** [comment] 2020-07-03 03:45
I also see the same behavior in 7.4.1

**Comment by xuzhg** [comment] 2020-07-03 06:35
@hemirunner426 would you please share your repro with me?

**Comment by hemirunner426** [comment] 2020-08-04 21:52
I think it had something to do with the data I was POSTing.  Doing this has worked for me in 7.4.1

Here is an example that works... I think the key is to make sure your POST content ype and media type are set correctly.  In my case, JSON.

`var testAction = new { Param1 = 100, Param2 = "TEST DATA", ShouldExecute = true };
var payload = new StringContent(JsonConvert.SerializeObject(testAction), Encoding.UTF8, "application/json");
            payload.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");
            var response = await platform.Client.PostAsync(url, payload);`

**Comment by xuzhg** [comment] 2020-09-14 21:24
I think the problems got resolved in this issue. If you think it's not, please file new issue or reopen it.

**Closed by xuzhg** 2020-09-14 21:24 UTC
Labels: Investigated

**Comment by tomvanoost** [comment] 2020-09-30 14:05
Verified. It works for me in 7.4.1.

**Comment by chen1tian** [comment] 2023-06-07 06:57
If the parameter is a DTO and a non-nullable property is passed with a null value, it will result in the entire ODataActionParameters being null. This is particularly common with string properties, which are often passed with empty values. To solve this issue, either change the property to nullable (e.g., public string? Name) or add the [Required] attribute.
