### ISSUE TITLE
AspNetCore ODataBatchRequestItem swallows inner request exceptions

### ISSUE THREAD

**Issue by AdamCaviness** [OData/WebApi#2245] opened 2020-08-10 20:51 UTC
*`ODataBatchRequestItem.SendRequestAsync()` swallows all exceptions thrown while processing inner requests and does not attempt to utilize any `ILogger` service implemented in an aspnetcore app. This means whenever an exception is thrown, no information can be found via **any** logging strategy.*

### Assemblies affected

*OData WebApi lib 7.4.1*

### Reproduce steps

*Derive a `DefaultODataBatchHandler` and utilize it as the `ODataBatchHandler`. Perform a Batch DELETE (probably any verb will do) and in your DELETE action, throw an exception.*

### Expected result

*A Microsoft.Extensions.Logging.`ILogger` implementation should be able to log the exception. If no `ILogger` can be found, the exception should be re-thrown.*

### Actual result

*With or without an `ILogger` implementation, nothing about the exception is logged!!*

### Additional detail

*The `ODataInputFormatter` class makes use of the `ILogger` service so we have a valid precedence to depend on any `ILogger` implementation but it wasn't utilized in the `ODataBatchRequestItem` class. I propose that `ODataBatchRequestItem` **also** try to get an `ILogger` implementation.*

```
catch (Exception ex)
{
	ILogger logger = context.RequestServices.GetService<ILogger>();
	if (logger == null)
	{
		throw;
	}

	logger.LogError(ex, String.Empty);

	// Unlike AspNet, the exception handling is (by default) upstream of this middleware
	// so we need to trap exceptions on our own. This code is similar to the
	// ExceptionHandlerMiddleware class in AspNetCore.
	context.Response.Clear();
	context.Response.StatusCode = 500;
}
```

**Comment by marabooy** [comment] 2020-08-11 17:41
Hi @AdamCaviness thank you for your report this seems to be a duplicate of #2244 so closing it.

**Closed by marabooy** 2020-08-11 17:41 UTC
