### ISSUE TITLE
Typeless scenario and $filter operator

### ISSUE THREAD

**Issue by MaxWilsonMS** [OData/WebApi#411] opened 2015-06-19 23:56 UTC
Hi,

I've got a scenario where I'm implementing typeless oData as described at http://blogs.msdn.com/b/leohu/archive/2013/11/05/typeless-entity-object-support-in-webapi.aspx. All of my controllers return an IEdmObject object which also implements IQueryable<MyEdmObject>. All this works just fine for pure Get() operations, but when I try to implement support for $filter, I get an error. 

```
        var retval = options.ApplyTo(query, new ODataQuerySettings()).OfType<MyEdmObject>();
        return retval;
```

The ApplyTo call fails when it tries to create an ODataQueryContext because that ODataQueryContext assumes that each CLR type (in this case, MyEdmObject) can be uniquedly mapped to an IEdmType. But that's precisely the requirement I'm trying to escape by using typeless entities!

Am I operating at the wrong level of abstraction? Maybe ApplyTo() is only allowed in the CLR-typed scenario and I need to implement my own ApplyTo? Any guidance would be appreciated.

-Max

**Comment by congysu** [comment] 2015-06-24 07:56
Related issue #165, #175.

**Comment by mikepizzo** [comment] 2017-08-02 23:40
Closing as dupe of issue #165.

**Closed by mikepizzo** 2017-08-02 23:40 UTC
Labels: backlog, P4
