### ISSUE TITLE
Update dependencies for .net core 2.0 package dependencies

### ISSUE THREAD

**Issue by hikalkan** [OData/WebApi#1059] opened 2017-08-17 10:42 UTC
Microsoft.AspNet.OData package has following dependencies:

- Microsoft.Extensions.DependencyInjection (>= 1.0.0 && < 2.0.0)
- Microsoft.Extensions.DependencyInjection.Abstractions (>= 1.0.0 && < 2.0.0)

As you have seen it depends on older version of the packages. So, they are preventing me to upgrade my solution to use new versions of these packages.

Have you planned to upgrade it?

**Comment by genusP** [comment] 2017-08-17 12:34
See PR #1058

**Comment by hikalkan** [comment] 2017-08-17 12:40
Thank you, that's very good :)

**Comment by JanEggers** [comment] 2017-09-26 11:11
@xuzhg : are there any builds of this? on your myget feed there is only Microsoft.AspNet.OData but no Microsoft.AspNetCore.OData

**Comment by xuzhg** [comment] 2017-09-26 16:47
@JanEggers No. See the comments from https://github.com/OData/WebApi/issues/939

**Comment by millman82** [comment] 2017-10-18 19:23
@genusP The linked PR seems to be only adding this support for Microsoft.AspNetCore.OData. Is this going to be updated for Microsoft.AspNet.OData? We're converting some of our shared libs to .NETStandard 2.0 and we've replace Unity with Microsoft.Extensions.DependencyInjection. I need the ability to use Microsoft.Extensions.DependencyInjection 2.0.0 in conjunction with Microsoft.AspNet.OData.

**Comment by genusP** [comment] 2017-10-19 05:37
@millman82  PR #1082 add compatibility with Microsoft.Extensions.DependencyInjection 2.0.0

**Comment by ismcagdas** [comment] 2018-01-17 07:13
Are there any progress on this ?

**Comment by justintoth** [comment] 2018-03-28 15:41
+1

**Comment by titobf** [comment] 2018-04-25 18:07
+1

**Comment by justintoth** [comment] 2018-05-02 13:10
Still completely blocked on upgrading our odata api to the latest nuget packages, due to Microsoft.AspNet.OData not supporting DI 2.x. It's not as trivial as wanting to upgrade nuget packages, we have other shared code that uses the latest nuget packages, so it means we can't even reference our other shared libraries in our odata api project, it's completely quarantined for the time being. It's not like this is a 3rd party package, this is from Microsoft itself, so it's really disappointing that you wouldn't stay up to date. Someone, please fix this, we've been waiting almost a year now....

**Comment by lesair** [comment] 2018-05-02 13:11
Any ETA for this yet?

**Comment by cilerler** [comment] 2018-05-02 13:41
P4?  It should be P1, just saying

**Comment by kieseld** [comment] 2018-05-02 16:49
Blocking issue for us as well.

**Comment by lesair** [comment] 2018-05-02 17:09
@kieseld You're not alone. Blocking us too here.

**Comment by stephenpope** [comment] 2018-05-03 13:16
Blocked also.

**Comment by cilerler** [comment] 2018-05-03 13:36
Please also click on 👍 in the initial request, so owner can see at first glance this shouldn't be P4

**Comment by lesair** [comment] 2018-05-03 14:30
@cilerler Done.

**Comment by justintoth** [comment] 2018-05-03 14:54
It doesn't seem to be as simple as the package owner just upgrading the DI nuget packages. I forked their repo and tried the upgrade myself, but was blocked because the DI 2.0 nuget packages require .NET Standard 2.0 and the Microsoft.AspNet.OData project is .NET Framework v4.5. I tried upgrading it to v4.7.1 but still no dice. See my [SO post](https://stackoverflow.com/questions/50157978/installing-microsoft-extensions-dependencyinjection-in-net-framework-4-7-1-proj), and let me know if you can think of a way around this block.

**Comment by stephenpope** [comment] 2018-05-03 15:17
@justintoth This is exactly what I've started to do today. The reasons you listed in your SO post are pretty much identical to mine. We have a product we are trying to upgrade to use netcore 2.0 libraries even though we still run some parts on full framework and this is where we ran into this issue. If I figure anything out I'll let you know !

**Comment by stephenpope** [comment] 2018-05-04 10:46
**!! Hack warning !!**

Thought I would post what we found when looking at ways to get around this .. you can disable some error/warning messages using the MSBuild features if you are using PackageReferences in your `csproj` (rather than using `packages.config`) 

```
<ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0">
        <NoWarn>NU1608</NoWarn>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.0.0">
        <NoWarn>NU1608</NoWarn>
    </PackageReference>
    <PackageReference Include="Microsoft.Aspnet.Odata" Version="6.1.0">
</ItemGroup>
```
So your project *should* now build happily so you get DI v2 + oData 6.10 .. but then the issue is the breaking change between DI 1.0 + DI 2.0.

Then you can look at how to replace the `DefaultContainerBuilder` implementation with the reflection based one from #1082 - which works with DI v1 + DI v2 (but is in the master branch for 7.0.0).

Hopefully this can be achieved using what is talked about here:  https://odata.github.io/WebApi/13-04-DependencyInjection/

Still would be better if this was fixed officially :)

**Comment by justintoth** [comment] 2018-05-04 12:07
@stephenpope I went down this path originally, unfortunately I found that it made it so that the nuget package manager would no longer upgrade ANY package. Let me know what your experience is.

**Comment by cilerler** [comment] 2018-05-04 21:27
@stephenpope I appreciate if you may share a sample repository that demonstrates it so far no luck on my end.  😭 🔮

**Comment by xuzhg** [comment] 2018-05-17 00:50
@christophwille  @justintoth @stephenpope @cilerler @hikalkan and others

Would you please try the nightly build **Microsoft.AspNet.OData**, version 7.0.0-Nightly201805162258.
The source is: https://www.myget.org/F/webapinetcore/api/v3/index.json

![image](https://user-images.githubusercontent.com/9426627/40150858-090cb282-5931-11e8-8b3f-73d96b15f62e.png)

It seems work at my side, please make sure what i did correct:

1 . VS2017, create a console application with classic windows desktop
2. Install nightly package. Version 7.0.0-Nightly201805162258
3. Write some codes in the program.cs.
for example:
```c#
    class Program
    {
        static void Main(string[] args)
        {
            var builder = new ODataConventionModelBuilder();
            builder.EntitySet<Customer>("Customers");
            IEdmModel model = builder.GetEdmModel();

            foreach (var element in model.SchemaElements)
            {
                Console.WriteLine(element.Name);
            }
        }
    }

    class Customer
    {
        public int Id { get; set; }
    }
```
4. Build and run. you will get result.
5. Go to nuget package manager
6. Update the dependencyinject to version 2.0
7. Build & run. you will get the same result.

Please try and let me know any concern.

**Comment by christophwille** [comment] 2018-05-17 06:03
Did a test on our real solution (heck, that's why we have source control). Target FW 4.6.2.

Step 1 - added the Nuget you specified. Had to touch a total of 14 files. (old was 6.1)

using System.Web.OData; -> using Microsoft.AspNet.OData;
using System.Web.OData.Routing;  -> using Microsoft.AspNet.OData.Routing;
using System.Web.OData.Builder; -> using Microsoft.AspNet.OData.Builder;
(and a few more similar to those)

Runs as before (msgraph calls, az storage, you name it)

Step 2 - added EF Core 2.0.3 (which didn't work before). That worked.

Step 3 - referenced our EF Core project into the Web. Tried a context. Worked.

So can confirm this fixes a real-world project. (but we cannot use the nightly, obviously)

**Comment by xuzhg** [comment] 2018-05-17 16:35
@christophwille Thanks for your trying.

**Comment by justintoth** [comment] 2018-05-18 12:48
@xuzhg @christophwille How are you guys installing the nightly build?

> PM> Install-Package Microsoft.AspNet.OData -Version 7.0.0-Nightly201805162258
>   GET https://api.nuget.org/v3/registration3-gz-semver2/microsoft.aspnet.odata/index.json
>   OK https://api.nuget.org/v3/registration3-gz-semver2/microsoft.aspnet.odata/index.json 199ms
> Install-Package : Unable to find version '7.0.0-Nightly201805162258' of package 'Microsoft.AspNet.OData'.
> At line:1 char:1
> + Install-Package Microsoft.AspNet.OData -Version 7.0.0-Nightly20180516 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Time Elapsed: 00:00:00.4022642

**Comment by cilerler** [comment] 2018-05-18 12:50
@justintoth you need to target https://www.myget.org/F/webapinetcore/api/v3/index.json not **nuget**

**Comment by justintoth** [comment] 2018-05-18 12:53
Just figured that out, never used a source other than nuget before. Unfortunately it didn't work for me, the nightly build still shows as not supporting DI 2.0.

![odata](https://user-images.githubusercontent.com/1443831/40235644-e78f1d72-5a78-11e8-90f4-133ff8251e81.PNG)

> Restoring packages for C:\RPR-AMP-Upstream\Dev\MetaMan\MetaMan.Api\MetaMan.Api.csproj...
>   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.odata/index.json
>   GET https://www.myget.org/F/webapinetcore/api/v3/flatcontainer/microsoft.aspnet.odata/index.json
>   OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.odata/index.json 523ms
>   OK https://www.myget.org/F/webapinetcore/api/v3/flatcontainer/microsoft.aspnet.odata/index.json 4563ms
>   GET https://www.myget.org/F/webapinetcore/api/v3/flatcontainer/microsoft.aspnet.odata/7.0.0-Nightly201805181243/microsoft.aspnet.odata.7.0.0-Nightly201805181243.nupkg
>   OK https://www.myget.org/F/webapinetcore/api/v3/flatcontainer/microsoft.aspnet.odata/7.0.0-Nightly201805181243/microsoft.aspnet.odata.7.0.0-Nightly201805181243.nupkg 3471ms
> Installing Microsoft.AspNet.OData 7.0.0-Nightly201805181243.
> Version conflict detected for Microsoft.Extensions.DependencyInjection.Abstractions. Reference the package directly from the project to resolve this issue. 
>  MetaMan.Api -> Common.Logging -> Serilog.Extensions.Logging 2.0.2 -> Microsoft.Extensions.Logging 2.0.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 2.0.0) 
>  MetaMan.Api -> Microsoft.AspNet.OData 7.0.0-Nightly201805181243 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 1.0.0 && < 2.0.0).
> Package restore failed. Rolling back package changes for 'MetaMan.Api'

**Comment by xuzhg** [comment] 2018-05-18 16:37
@justintoth Please select version: **7.0.0-Nightly201805162258** to try. 

  Not all version can work because i haven't merge my PR yet.

**Comment by xuzhg** [comment] 2018-05-21 21:05
Merged the PR. #1440. Please let us know if you have further concerns or questions.

**Closed by xuzhg** 2018-05-21 21:05 UTC
Labels: P1
