### ISSUE TITLE
Microsoft.OData.ODataException: 'Found an unresolved path segment 'xxx' in the OData path template 

### ISSUE THREAD

**Issue by jannikbuschke** [OData/WebApi#2151] opened 2020-05-07 07:10 UTC
Using a controller like this
```cs
   public class PersonsController : ODataController
    {
        private readonly DataContext ctx;

        public PersonsController(DataContext ctx)
        {
            this.ctx = ctx;
        }

        [EnableQuery]
        public SingleResult<Person> GetPerson(Guid key)
        {
            return new SingleResult<Person>(ctx.Persons.Where(v => v.Id == key));
        }

        [EnableQuery]
        public IQueryable<Person> GetPersons()
        {
            return ctx.Persons;
        }
    }
```

Gives me an 
```
Microsoft.OData.ODataException: 'Found an unresolved path segment 'Person' in the OData path template 'Persons/{key}/Person'.'
```
at Startup when calling
```
builder.MapVersionedODataRoutes("odata", "odata", modelBuilder.GetEdmModels());
```

### Assemblies affected

```
netcoreapp3.1
Microsoft.AspNetCore.OData Version=7.4.0
Microsoft.AspNetCore.Mvc.Versioning Version=4.1.1
Microsoft.AspNetCore.OData.Versioning Version=4.1.1
```

### Reproduce steps

```
git clone https://github.com/jannikbuschke/pragmatic-cqrs-with-asp-net-core-for-spas.git
git checkout e88d7362c2ffcc42b1f8d2f509ab4f0e5eca0386
run Sample4 with dotnet
````

### Expected result

App should start

### Actual result

App crashes at startup with above mentioned exception

### Additional detail

It seems that the conventional naming in the controller does not get picked up.
I.e. the `GetPerson(Guid key)` is not recognized as a valid route. Using unnamed routes:
```cs
       [EnableQuery]
        public SingleResult<Person> Get(Guid key)
        {
            return new SingleResult<Person>(ctx.Persons.Where(v => v.Id == key));
        }

        [EnableQuery]
        public IQueryable<Person> Get()
        {
            return ctx.Persons;
        }
````
allows the app to start normally, and the controller seems to work.
See https://github.com/jannikbuschke/pragmatic-cqrs-with-asp-net-core-for-spas/commit/cb28046ba9f93b7d4ebd038014699483024359ed

**Comment by henrikdahl8240** [comment] 2020-05-08 21:56
@jannikbuschke Perhaps you could also include the few lines from your model builder, which builds the entity set and the type, please?

**Comment by henrikdahl8240** [comment] 2020-05-09 21:28
Perhaps you could try to program your method like this instead:
```
[EnableQuery]
public ActionResult<SingleResult<Person>> GetPerson([FromODataUri] System.Guid key)
{
    return Ok(SingleResult.Create(ctx.Persons.Where(x => x.ID == key)));
}

```

Does it work correctly now?

**Comment by jannikbuschke** [comment] 2020-05-11 17:56
This is the corresponding modelbuilder: 
https://github.com/jannikbuschke/pragmatic-cqrs-with-asp-net-core-for-spas/blob/cb28046ba9f93b7d4ebd038014699483024359ed/4-cqrs-with-mediatr-and-odata/OdataModelConfiguration.cs

```cs
    public class OdataModelConfiguration : IModelConfiguration
    {
        public void Apply(ODataModelBuilder builder, ApiVersion apiVersion)
        {
            builder.EntitySet<Person>("Persons");
        }
    }
```


Using an ActionResult as return type yields the same error.

Actually I am fine with just naming my methods `Get`, so I personally don't see it as any issue anymore.

**Comment by henrikdahl8240** [comment] 2020-05-11 19:13
You do not have the `[FromODataUri]` attribute, which is the reason it didn't work for you.

**Comment by gathogojr** [comment] 2020-05-12 16:51
@jannikbuschke I think need to add the `ApiVersion` attribute to the controllers since you're using `MapVersionedODataRoutes`. Kindly take a look at the following resources:
https://github.com/microsoft/aspnet-api-versioning/wiki/New-Services-Quick-Start
https://github.com/microsoft/aspnet-api-versioning/wiki/OData-Versioned-Controllers

**Comment by gathogojr** [comment] 2020-05-12 17:45
@jannikbuschke I did a quick repro and confirm that the issue is fixed by doing the following:
Rename, respectively:
```
public IQueryable<Person> GetPersons()
public SingleResult<Person> GetPerson(Guid key)
```
to
```
public IQueryable<Person> Get()
public SingleResult<Person> Get([FromODataUri] Guid key)
```

That alone will be enough to allow your service to be bootstrap and run successfully

In addition, if you hope to apply api version when calling your service, you'll need to apply `AppVersion` attribute to your controller like so:
```
    [ApiVersion("1.0")]
    public class PersonsController : ODataController
```
However, I also realized that so long as you pass `api-version` as `1.0`, you really don't need to apply the attribute:
`http://ServiceRoot/Persons?api-version=1.0` or
`http://ServiceRoot/Persons/00000000-0000-0000-0000-000000000000?api-version=1.0`

This will not work without the relevant `ApiVersion` attribute:
`http://ServiceRoot/Persons?api-version=2.0`

**Comment by gathogojr** [comment] 2020-05-12 18:03
@jannikbuschke This works too
```
[EnableQuery]
[ODataRoute("Persons")]
public IQueryable<Person> GetPersons()
...

[EnableQuery]
[ODataRoute("Persons/{key}")]
public SingleResult<Person> GetPerson([FromODataUri]Guid key)
...
```

**Closed by gathogojr** 2020-05-12 18:03 UTC
