### ISSUE TITLE
Encoded single quotes are not decoded by the OData Library

### ISSUE THREAD

**Issue by kalavany** [OData/WebApi#2051] opened 2020-02-13 22:00 UTC
*Short summary (3-5 sentences) describing the issue.*

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData WebApi lib 6.1.0

### Reproduce steps

http://aurorav76353.aurorav76353dom.extest.microsoft.com/CITTest/api/data/v9.0/GetEntityWiseDuplicatesCount%28Entity%3D%40Entity%29?%40Entity=%7b%22%40odata.type%22%3A%22%23Microsoft.Dynamics.CRM.account%22%2c%22name%22%3A%22O%27%27Neil%22%2c%22statuscode%22%3A1%2c%22statecode%22%3A0%7d

### Expected result

When O'Neil is sent as O''Neil in the uri as per odata documentation to encode the single quote with two single quotes, the odata library should decode it as one single quote and treat it as O'Neil 

### Actual result

Server gets it as O''Neil and the results of the query are not as expected as there is no O''Neil in the system

### Additional detail

Similar issue was fixed as part of the commit https://github.com/OData/odata.net/issues/1313 but it is for operators like contains and concat. The above mentioned case needs to be handled too.

**Comment by gathogojr** [comment] 2020-02-20 05:28
@kalavany Security restrictions cannot allow me to access the repro link you shared above. Could you kindly cite exact cases where the behaviour is not as expected. It did try using $filter with `eq` and I get back the expected results:
Example: `<ServiceRoot>/Movies?$filter=Name eq 'Schindler''s List'`
Result:
```
{
    "@odata.context": "<ServiceRoot>/$metadata#Movies",
    "value": [
        {
            "Id": 3,
            "Name": "Schindler's List",
            "RunningTime": 195
        }
    ]
}
```
I used the following tools and packages to verify:
- Microsoft.AspNet.OData (6.1.0)
- Microsoft.EntityFrameworkCore (3.1.0)
- .NET Framework 4.7.2
- Visual Studio 2017

**Comment by gathogojr** [comment] 2020-03-04 09:58
@kalavany Are you still experiencing an issue with single quotes in the Uri or can I proceed to close this issue? Find above the outcome of my investigation

**Comment by kalavany** [comment] 2020-03-07 00:49
Hi John

I see that you have used $filter in the below. But my issue is regarding the string with two single quotes inside a Function parameter. Can you try creating a function that has entity as a parameter and in the entity you specify a string attribute that contains two single quotes.

Thanks,
Lavanya

**Comment by gathogojr** [comment] 2020-03-09 04:58
@kalavany I'll try it out on a function and revert

**Comment by gathogojr** [comment] 2020-03-10 08:27
@kalavany Finally managed to reproduce the issue. It happens specifically when using an EntityParameter - for both bound and unbound function (probably action too). See the attached screenshot
![image](https://user-images.githubusercontent.com/28291332/76292209-d4ff5400-62bf-11ea-9916-030976b34139.png)
Where the request Uri looks like this 
http://ServiceRoot/GetRating(actor=@p)?@p={'@odata.type':'%23NS.Actor','Id':1,'Name':'Patrick O\'\'Neal'}

The [OData spec](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_URLSyntax) requires the two consecutive single quotes but it'd seem that when used in a JSON representation of an entity it doesn't get decoded properly on the service side so it still appears with consecutive single quotes 

Its decoded okay for simple primitive types parameters: 
http://ServiceRoot/GetLength(input=@p)?@p='Patrick O''Neal'
![image](https://user-images.githubusercontent.com/28291332/76292774-ded58700-62c0-11ea-8a60-05a5ad03932f.png)

Thank you for reporting the issue. We'll look into getting it fixed
cc. @mikepizzo @xuzhg @mumbi-o @odero

**Comment by kalavany** [comment] 2020-03-10 17:35
Sure, Thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gathogojr** [comment] 2020-05-24 15:55
@kalavany FYI, issue fixed in this ODL PR https://github.com/OData/odata.net/pull/1783

**Closed** 2020-05-24 15:56 UTC
Labels: P3, bug
