### ISSUE TITLE
Performance kill when using $expand and the model has many entities and actions.

### ISSUE THREAD

**Issue by CarlosMontagut** [OData/WebApi#2001] opened 2020-01-03 14:33 UTC
[TestExpand.zip](https://github.com/OData/WebApi/files/4019441/TestExpand.zip)

When requesting an entity collection with a simple $expand of a many to one relation, performance is killed when the model has many entities and actions defined (not related with the entity requested, about 200 entities with 20 actions each).

If the model has only two entities, requesting the collection with the $expand takes around 150ms. If you add to the model the 200 entities with 20 actions each, the request takes 20/30 times more. 

The bigger the model, the bigger the performance is killed.

If I remove the $expand in the request, performance is good.

### Assemblies affected

Microsoft.AspNet.OData 7.3

### Reproduce steps

1. Define two entities, ObjectDummy and ObjectDummy2. ObjectDummy has a reference to ObjectDummy2 called Campo8
2. Request http://localhost:59703/api/odata/ObjetoDummy?$expand=Campo8
3. Result is ready in about 150ms
4. Define 200 more entities (not related to ObjectDummy), and define 20 actions on each entity.
5. Request same http://localhost:59703/api/odata/ObjetoDummy?$expand=Campo8
6. Result is ready in about 3s / 5s

The more entities and action define, the more the performance is killed.

### Expected result

Performance shouldn't be affected in that grade when there are more entities in the model

### Actual result

Performance is killed, take around 20 / 30 times more (and even more if the model grows).

### Additional detail

I attach a simple proyect that demonstrate it. In the WebApiConfig.cs (line 95) there is a code to uncomment and check the performance with or without the additional entities).

**Comment by KanishManuja-MS** [comment] 2020-01-07 17:27
@CarlosMontagut Thanks for submitting the issue. We will look into it and get back.

**Comment by CarlosMontagut** [comment] 2020-01-07 17:48
Thanks! @KanishManuja-MS let me know if you need any information or sample !

**Comment by CarlosMontagut** [comment] 2020-01-09 14:20
@KanishManuja-MS  / @odero 

I think I found the performance problem. 

The method GetEdmType in SelectExpandWrapper is calling model.GetEdmTypeReference(elementType). The bigger the model, the longer it takes for GetEdmTypeReference to return the EdmType.

 It only happend when you use $expand in the ODATA query string.

In my case, I was quering a full entity set wtih $expand, and the result returned N entities, calling GetEdmType N times.

I did a test using a simple cache and calling GetEdmTypeReference only if I have a cache miss, and the performance rocket.

Don't know if the cache will be a suitable solution, or you would like to go deeper and check why GetEdmTypeReference is taking so long when the model is big.

Let me know your thoughts and I can try to do a pull request.

Regards!

Carlos

[https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/Query/Expressions/SelectExpandWrapper.cs](url)

**Comment by habbes** [comment] 2020-01-09 14:44
Hi @CarlosMontagut, thanks for sharing your findings. I was able to reproduce your issue and noticed the drastic performance drop. Yes, you could create a PR so we can better look at your solution.  Or share relevant snippets. In the meanwhile I'll also try to attempt the solution you have described and will get back if I have additional insights.

**Comment by CarlosMontagut** [comment] 2020-01-09 14:50
Hi @habbes, 
I just put a basic cache in the method I mentioned and worked for the test I was doing, but probably the final solution should be a cache per model or something a bit more complex.
Do you think is worth it to check the implementation of IEdmModel to check why GetEdmTypeReference is taking so much time to return when the model is big ?

**Comment by habbes** [comment] 2020-01-09 14:58
Also an additional check I forgot to ask @CarlosMontagut, how much performance gain did you observe, was the new request execution time similar to the performance you get when you only have 2 entities in your model? Or do you still observe some considerable performance drop as a result of adding more entities?

**Comment by habbes** [comment] 2020-01-09 15:03
@CarlosMontagut Yes, I do think it's worthwhile to find out why `GetEdmTypeReference` takes long for large models.

**Comment by CarlosMontagut** [comment] 2020-01-09 15:27
@habbes, this are my findings quering 2000 Dummy1 entities with a $expand to a Dummy2 entity.

(I did three request, the first one takes longer due initialization).

CACHE (in SelectExpandWrapper.GetEdmType) + 2 ENTITIES + 500 ENTITIES with 100 ACTIONS EACH
742
162
155

CACHE (in SelectExpandWrapper.GetEdmType) + 2 ENTITIES
666
149
134

NO CACHE + 2 ENTITIES
711
185
169

NO CACHE + 2 ENTITIES + 500 ENTITIES with 100 ACTIONS EACH
49618
49191
49132

So, with the cache, is taking a bit longer when you use a big model, but doesn't look so bad.

**Comment by habbes** [comment] 2020-01-09 15:35
Thanks @CarlosMontagut

**Comment by CarlosMontagut** [comment] 2020-01-09 17:04
@abbe
I have been doing some more research.

The method GetEdmTypeReference of the model class is an extension method from this project.

The sequence is:

SelecExpandWrapper ->
EdmLibHelpers.GetEdmTypeReference() ->
EdmLibHelpers.GetEdmType() ->
EdmLibHelpers.GetEdmType(Model, Type, bool) 

There we find these sentence:
     
IEdmType returnType =
edmModel
.SchemaElements
.OfType<IEdmType>()
.Select(edmType => new { EdmType = edmType, Annotation = edmModel.GetAnnotationValue<ClrTypeAnnotation>(edmType) })
.Where(tuple => tuple.Annotation != null && tuple.Annotation.ClrType == clrType)
.Select(tuple => tuple.EdmType)
.SingleOrDefault();

I think this Select expression in the SchemaElements is what is taking down the performance when the model is big.

I think a cache in the GetEdmType(Model, Type, bool) method could improve performance in all the library since is been use from many places.

**Comment by habbes** [comment] 2020-01-10 07:39
Hi @CarlosMontagut
I investigated the bug a bit further and found that we had a mistake in one of the assumptions.
When you call `builder.EntityType<DummyObject>()` multiple times, it will essentially returning the same entity. So your for loop with 200 iterations is creating 200 entity sets, however there are still only 2 entities.
So it's not the number of entities or entity sets that slowed down performance in your tests. It was actually the number of actions. Because you're always working with the same entity, your nested loop essentially creates close to 200 * 20 = 4000 actions bound to the same entity. You can confirm this by looking at the `/$metadata` endpoint.

I have tried creating a separate entity class that is not involved in the request, and I have bound the actions to that entity instead. The result was the same, there was still as significant performance drop using `$expand` even though these actions are bound to an entity that has nothing to do with the request.

Additionally, I tried creating the same number of unbound actions instead of bound actions and observed a similar performance drop.

This  of course does not change the fact that your solution works and so far seems right. But I would like to investigate the issue a bit more to see whether there's something else we missed and to understand better what causes it and under which conditions.

**Comment by habbes** [comment] 2020-01-10 07:51
@CarlosMontagut the same behaviour is observed when adding many functions. So you were generally right that the performance drop occurs when the model is large.

**Comment by habbes** [comment] 2020-01-10 09:27
@CarlosMontagut you could go ahead and create a PR and we can review. But I'm still investigating this issue and will let you know if I get any additional insights.

**Comment by CarlosMontagut** [comment] 2020-01-10 11:21
Hi @habbes, 

Yes, you are right about the fact that the loop of 200 calls to builder.EntityType<DummyObject>() create only one entity in the $metadata, that was the reason I later called to create unbound actions to make the model bigger.

In my real model the 200 entities are diferent classes (this is where I found the issue).

I think what make the performance drop, is the ammount of different 'objects' (doesn't matter if they are entities, complextypes, functiones, actions, etc), that end up in the edmModel
.SchemaElements attribute, where we later do a linq Select.

The problem getes worse because in the test, we are requesting 2000 entities Dummy1, and each has a referece to Dummy2, so the select on edmModel
.SchemaElements is calle 1+2000 times (even if the 2000 times are to get the same EdmType).

I would create a PR so you can review it in deep.

**Comment by CarlosMontagut** [comment] 2020-01-10 12:52
@habbes PR created

[https://github.com/OData/WebApi/pull/2014](https://github.com/OData/WebApi/pull/2014)

As I mentioned in the PR, the solution has a static cache, with has as a key the model. The cache will be holding a reference to the model, wich might be a memory problem if there is an escenario where models are create and discarded often. An option could be to use a hash of the model or any other unique identity that the model could have.

**Comment by habbes** [comment] 2020-01-10 16:17
@CarlosMontagut I would like to add a little more insight to this issue after conducting more investigations:

`GetEdmType()` is called from a number of places, for example `OdataOutputFormatterHelper` and `ResourceContext`.

It is also called many times for each entity:
- It is called for the `IEnumerable<Entity>` type.
- It is called for the `SelectExpandWrapper<Entity>` type

The calls to `GetEdmType()` with the above types are cached through the user of `model.GetTypeMappingCache().GetEdmType()`. However, when you call `GetEdmType(IEnumerable<Entity> collection, model)`, it does a recursive call to `GetEdmType(Entity, model)` to get the type of the entity contained by the collection. This recursive call to get the element type is not cached. And this is where the problem lies, because this is type is requested much more often than the edm type of the collection type.

In the case of an expand query, the `SelectExpandWrapper.GetEdmType()` is called numerous times for each entity:
- it is called when the edm type of the collection is requested
- it is called when the edm type of the wrapper is requested
- it is called for each property of the entity
- it is called for each property of the nested/expanded object
So in your examples of fetching 2000 entities with about 10 fields including a nested entity with about 10 more fields would have let to at least 200,000 calls. I'm not sure if this issue really occurs only in expand requests or whether it may occur in other requests but just would require a much larger model to notice.

**Comment by CarlosMontagut** [comment] 2020-01-10 16:54
@habbes Yes... I see...

Sounds that GetEdmType() shouldn't be used directly in any part of lib, and all that calls should go throw the ClrTypeCache (been this the only call to GetEdmType()).

> I'm not sure if this issue really occurs only in expand requests or whether it may occur in other requests but just would require a much larger model to notice.
Replacing all the GetEdmType calls by the use of the ClrTypeCache can give us an idea of performance impact, maybe adding more fields to the Dummy entities...

**Comment by habbes** [comment] 2020-01-10 18:02
@habbes 
> Sounds that GetEdmType() shouldn't be used directly in any part of lib, and all that calls should go throw the ClrTypeCache (been this the only call to GetEdmType()).

That's true. However, if `GetEdmType()` is called with a collection type, then it makes a recursive call to get the edm type of the element type. And this recursive call is not cached. And that's part of the problem.

**Comment by CarlosMontagut** [comment] 2020-01-10 19:04
@habbes I see... I will check in deep the code of the GetEdmType()...

**Comment by CarlosMontagut** [comment] 2020-01-13 12:12
Hi @habbes,

I have been digging down the GetEdmType() method. There are two:

1. A public one, that receives the edmModel and the clrType, which isbeen  used in 6 places in the lib, and can be easily replaced by the ClrTypeCache. The ClrTypeCache, calls this GetEdmType methods when cache fails, and the GetEdmType  method calls the private GetEdmType method (the next one) always with collections parameter in true.

2. A private one, that receives the edmModel, the clrType and a collection boolean parameter indicating if it has to try to get the type form the generic definition of an IEnumerable. This private method, call itself recursively in two points:
     2.a. when resolving the type from the collection, it calls recursively the private GetEdmType with the collection parameter in false.
     2.b. when resolving the type of superclass, with the same collection value that is been called.

Here will be a problem to replace these calls by the ClrTypeCache, that resolves the cache fail calling with the collection parameter always in true.

**Comment by habbes** [comment] 2020-01-13 13:58
Hi @CarlosMontagut,

You're right. It doesn't straightforward to make use of the cache in 2.a and 2.b without changing the public signature of `GetEdmType()` or adding methods to directly add and get entries from the `ClrTypeCache`.

**Comment by habbes** [comment] 2020-01-13 15:01
I'm also curious about the use of `SingleOrDefault()` as opposed to something like `FirstOrDefault()` in the `GetEdmType()` LINQ query. There's some performance gain when using `FirstOrDefault` since it doesn't scan the entire list, and no test seem to fail as a result of this change. The gain is not significant when we use caching, but I'm still curious to understand why it was important to ensure uniqueness.

**Comment by CarlosMontagut** [comment] 2020-01-13 16:17
@habbes, I have been looking at the points 2.a and 2.b, and that situations will not impact in performance very much, since it has a recursive call to GetEdmType, but only to get the collection type or the super class type. This will only happend when a new type is included in the cache (and happend once per collection, not once per item in the collection). 

I think changing the use of GetEdmType for the use of the cache in the all library, will really improve performance, and leaving the recursive call inside GetEdmType won't be a down in performance, since will only happend when a new type (or collection type) is introduce in the cache. 

Regarding your comments about SingleOrDefault vs FirstOrDefault, yes, FirstOrDefault will be faster, but don't know the consequences of not ensuring that we get a single result. Again, been a situation that will only happend once the first time a type is introduce in the cache, don't think will have a big impact.

Let me know your thoughts about it.

**Comment by habbes** [comment] 2020-01-13 16:31
@CarlosMontagut Thanks for taking a deeper look into it. I agree with your assessment. Will you make any additional changes?

**Comment by habbes** [comment] 2020-01-13 16:32
@CarlosMontagut I've added a summary of the discussion here to your pull request for the benefit of others who will review it. Could we continue this conversation over on the pull request instead of here?

**Comment by xuzhg** [comment] 2020-02-04 18:46
Merged at https://github.com/OData/WebApi/commits/master

**Closed by xuzhg** 2020-02-04 18:46 UTC
Labels: investigating
