### ISSUE TITLE
Wrong controller called when using endpoint routing with both WebApi and OData

### ISSUE THREAD

**Issue by maboivin** [OData/WebApi#2107] opened 2020-04-01 15:35 UTC
I'm trying to have both WebiApi (attribute routed) and OData in the same project and I'm running into an issue where when the OData route is matched, it calls the (wrong) WebApi controller. This issue has been created following my comment [here](https://github.com/OData/WebApi/issues/2029#issuecomment-599559382).

### Assemblies affected
Microsoft.AspNetCore.OData 7.4.0-beta

### Reproduce steps
I have created a simple repro project here: https://github.com/maboivin/WebApiAndODataIssue.

### Expected result
When calling the OData endpoint, it should call the right OData controller instead of the WebApi controller.

### Actual result
When calling the OData endpoint, it calls the wrong WebApi controller.

### Additional detail
Here's an extract of the logs when the route is matched but the wrong controller gets called:
```
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://localhost:26679/api/odata/users  
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path '/api/odata/users'
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'api/odata/{**ODataEndpointPath_odata}' with route pattern 'api/odata/{**ODataEndpointPath_odata}' is valid for the request path '/api/odata/users'
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint 'WebApiAndODataIssue.Api.WebApi.UsersController.Get (WebApiAndODataIssue)'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'WebApiAndODataIssue.Api.WebApi.UsersController.Get (WebApiAndODataIssue)'
```

And here's an extract of the logs when the route is matched but there's only the OData controller in the project:
```
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://localhost:26679/api/odata/users  
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path '/api/odata/users'
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'api/odata/{**ODataEndpointPath_odata}' with route pattern 'api/odata/{**ODataEndpointPath_odata}' is valid for the request path '/api/odata/users'
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint 'WebApiAndODataIssue.Api.OData.UsersController.Get (WebApiAndODataIssue)'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'WebApiAndODataIssue.Api.OData.UsersController.Get (WebApiAndODataIssue)'
```

I dug into the source code of the DfaMatcher and the EndpointRoutingMiddleware but couldn't find the right integration point so far. Are there any additional configurations needed? Do I need to override any service?

**Comment by xuzhg** [comment] 2020-04-01 19:00
Mixing WebAPI and OData controller is not recommended from OData perspective. Our OData action selector is too **naive** to distinguish from OData controller and WebAPI controller, especially the controller has the same name.  Sorry for that.

As a workaround, you can do like:

```C#
    public class MyActionSelector : IActionSelector
    {
        IActionSelector _selector;
        public MyActionSelector(IActionSelector selector)
        {
            _selector = selector;
        }

        public ActionDescriptor SelectBestCandidate(RouteContext context, IReadOnlyList<ActionDescriptor> candidates)
        {
            return _selector.SelectBestCandidate(context, candidates);
        }

        public IReadOnlyList<ActionDescriptor> SelectCandidates(RouteContext context)
        {
            var actionDescriptoers = _selector.SelectCandidates(context);

            List<ActionDescriptor> descriptors = new List<ActionDescriptor>();
            foreach (var action in actionDescriptoers)
            {
                if (action is ControllerActionDescriptor controllerAction)
                {
                    if (controllerAction.ControllerTypeInfo.BaseType?.Name == "ODataController")
                    {
                        descriptors.Add(action);
                    }
                }
            }

            return  descriptors;
        }
```

And change the startup.cs as:

```C#
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddHttpContextAccessor();
            services.AddControllers();
            services.AddOData();

            var selector = services.First(s => s.ServiceType == typeof(IActionSelector) && s.ImplementationFactory != null);
            services.Remove(selector);
            services.Add(new ServiceDescriptor(selector.ServiceType, selector.ImplementationFactory, ServiceLifetime.Singleton));
            services.AddSingleton<IActionSelector>(s =>
            {
                return new MyActionSelector((IActionSelector)selector.ImplementationFactory(s));
            });
        }
```

**Comment by mikepizzo** [comment] 2020-04-02 17:15
@xuzhg  -- let's make sure to cover this issue (mixing OData and WebAPI controllers) as a scenario in our .NET 5 planning.

**Comment by maboivin** [comment] 2020-04-07 17:26
Thanks for the workaround. I'm pretty confident I'll be able to make it work in my case for simple scenarios. I just didn't have enough time to try it in the past week.

I had also planned to use the API versioning and just saw that you created an issue (https://github.com/microsoft/aspnet-api-versioning/issues/616). I will monitor it because I'm interested in the result as well.

I also noticed you added the .NET 5 label. What does that mean? Do you expect to change the behavior in .NET 5?

Thanks again.

**Comment by maboivin** [comment] 2021-03-23 16:05
Hey @xuzhg,
I hope you're well.

I decided to pull the repro project and update it to see what was the behavior as of today.

My first try was to update to .NET 5 and OData 7.5.6 (latest released version). The behavior was exactly the same.

My second try was to update to OData 8.0.0-preview3 (latest preview version). Now, I get the following exception:
![image](https://user-images.githubusercontent.com/4491851/112177941-bf5d8380-8bcf-11eb-99b9-1e912300f43b.png)

Before I dig more into the conventions and the attribute routing, is the scenario described in the issue supposed to be supported by the time OData 8.0.0 is final?
 
Thanks.

**Comment by maboivin** [comment] 2021-05-10 13:20
Hey @xuzhg,
I updated to OData 8.0.0-rc2 and was able to make it work using the `[NonODataController]` attribute. I do think though that the web API controller shouldn't be considered because it has already another route defined that doesn't match.

Then, if I add a `[Route("api/odata/users")]` attribute to my OData controller ([in the repro project](https://github.com/maboivin/WebApiAndODataIssue/blob/59eae306510e1e7e003dcaceda7ba09af093933a/WebApiAndODataIssue/Api/OData/UsersController.cs#L11-L12)) and there's a match with, for example, the [entity set routing convention](https://github.com/OData/AspNetCoreOData/blob/8.0.0-rc2/src/Microsoft.AspNetCore.OData/Routing/Conventions/EntitySetRoutingConvention.cs), I get an ambiguous match for the same controller and same action. Is it expected?

See the exception details below:
```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

WebApiAndODataIssue.Api.OData.UsersController.Get (WebApiAndODataIssue)
WebApiAndODataIssue.Api.OData.UsersController.Get (WebApiAndODataIssue)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Let me know if it should be tracked in a separate issue.

Thanks.

**Comment by xuzhg** [comment] 2021-05-10 17:09
@maboivin Thanks for reaching to me.

Be noted, 8.0 also supports conventional and attribute routing together (by default).

The ambiguous exception is from the mix of attribute routing and conventional routing.

1. conventional routing:
    It takes the controller name and action name into consideration and build endpoint for any actions meet the conventional rule.
    Your "UsersController" and "Get()" method meets the entity set convention routing. So, entity set convention routing will build two endpoint for "Get()" method.
     * ~/api/odata/Users
     * ~/api/odata/Users/$count

2. Attribute routing

    It takes the routing attributes into consideration. The attributes have:
     * [ODataRoutingAttribute]
     * [RouteAttribute]
     * [HttpGetAttribute]
     * [HttpPostAttribute]
     * ....

Since your "UsersController" has "[Route("api/odata/users")]", it will build a new endpoint for "Get()" method.
    * ~/api/odata/users

So, you can see there are two "same" endpoint for "Get()". 
It's not a bug. It's by design, and customer should not mix the conventional and attribute routing together.

However, it still needs improvement. So, don't hesitate to share me your thought.

By the way, since RC2, you can enable "app.UseODataRouteDebug()" to see the built routes. Just send "~/$odata".

Thanks.

**Comment by KenitoInc** [comment] 2022-05-18 07:45
@maboivin Was this issue resolved? If yes we can close the issue

**Comment by KenitoInc** [comment] 2022-07-04 11:10
Closing this due to non response

**Closed by KenitoInc** 2022-07-04 11:10 UTC
Labels: follow up, Investigated, .NET 5
