### ISSUE TITLE
filtering by time throw parser error

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#85] opened 2015-01-12 01:30 UTC
The following query throws a parser error when it reaches the validate
expression end token:  
$filter=time(Timestamp)%20ge%2000:01  

    
    
    {
      "error":{
        "code":"","message":"The query specified in the URI is not valid. Syntax error at position 22 in 'time(Timestamp) ge 23:45'.","innererror":{
          "message":"Syntax error at position 22 in 'time(Timestamp) ge 23:45'.","type":"Microsoft.OData.Core.ODataException","stacktrace":"   at Microsoft.OData.Core.UriParser.ExpressionLexer.ValidateToken(ExpressionTokenKind t)\r\n   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseExpressionText(String expressionText)\r\n   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseFilter(String filter)\r\n   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, IEdmType elementType, IEdmNavigationSource navigationSource)\r\n   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseFilter()\r\n   at System.Web.OData.Query.FilterQueryOption.get_FilterClause()\r\n   at System.Web.OData.Query.Validators.FilterQueryValidator.Validate(FilterQueryOption filterQueryOption, ODataValidationSettings settings)\r\n   at System.Web.OData.Query.FilterQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at System.Web.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.OData.EnableQueryAttribute.ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions)\r\n   at ...    }
      }
    }

ALSO  
  
The following query throws a built in function not found error for $apply:  
$apply=filter(time(Timestamp)%20ge%2000:01)  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 1866](http://aspnetwebstack.codeplex.com/workitem/1866)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	cysu
**Reported on:**	Apr 22, 2014 at 9:03 PM
**Reported by:**	thebothead
**Updated on:**	Oct 23, 2014 at 7:54 PM
**Updated by:**	thebothead

**Comment by LianwMS** [comment] 2015-01-12 01:30
On *2014-05-26 13:36:02 UTC*, **fenzhao** commented:

ODL doesn’t support “time” function and parse Edm.TimeOfDay uri literal.

**Comment by LianwMS** [comment] 2015-01-12 01:30
On *2014-05-29 12:51:39 UTC*, **cysu** commented:

yjhong would help to check if the response code is 400 or not.

**Comment by LianwMS** [comment] 2015-01-12 01:30
On *2014-05-30 05:41:15 UTC*, **yjhong** commented:

I tested the following scenarios with OData V3 5.1 and 5.2, and OData V4 5.2.

http://localhost/odata/Orders?$filter=Foo(TimeStamp)%20ge%2000:01
 http://localhost/odata/Orders?$apply=filter(time(TimeStamp)%20ge%2000:01) http://localhost/odata/Orders?$filter=time(TimeStamp)%20ge%2000:01 http://localhost/odata/Orders?$filter=time(TimeStamp)%20ge%2000:01 All of them returns the 400 error.

**Comment by LianwMS** [comment] 2015-01-12 01:30
On *2014-05-31 01:00:06 UTC*, **yjhong** commented:

** Closed by yjhong 05/30/2014 10:00AM

**Comment by LianwMS** [comment] 2015-01-12 01:30
On *2014-05-31 04:19:34 UTC*, **yjhong** commented:

I changed the status to Resolve, and assign it to Congyong. Please close this bug.

**Comment by LianwMS** [comment] 2015-01-12 01:30
On *2014-06-05 08:51:24 UTC*, **cysu** commented:

yjhong verified that response code is 400.

** Closed by cysu 06/04/2014 5:51PM

**Comment by LianwMS** [comment] 2015-01-12 01:30
On *2014-10-24 02:54:52 UTC*, **thebothead** commented:

The 
OData specification shows that this should be supported. I am not familiar with the other ODL specification that has been referenced, however this should be supported when using OData on top of the web stack.


5.1.1.4.19 time 

The time function has the following signature: 

Edm.TimeOfDay time(Edm.DateTimeOffset) 

The time function returns the time part of the DateTimeOffset parameter value, evaluated in the time zone of the DateTimeOffset parameter value.


Services that are unable to preserve the offset of Edm.DateTimeOffset values and instead normalize the values to some common time zone (i.e. UTC) MUST fail evaluation of the time function for literal Edm.DateTimeOffset values that are not stated in the time
 zone of the normalized values.

**Comment by congysu** [comment] 2015-03-24 07:00
@xuzhg See if this gets fixed with the time() support.

**Comment by VikingsFan** [comment] 2015-03-24 08:30
This is fixed, can see the test EnableQueryTests, the way you construct filter is wrong, according to  odata [abnf ](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/abnf/odata-abnf-construction-rules.txt) :
timeOfDayValue = hour ":" minute [ ":" second [ "." fractionalSeconds ] ]

hour   = ( "0" / "1" ) DIGIT
       / "2" ( "0" / "1" / "2" / "3" ) 

hour can be 01 to 23, 2000 is not valid.
Please reopen it if you have any concern.

**Comment by thebothead** [comment] 2015-03-24 13:09
Come on guys...

The original query is not wrong:
$filter=time(Timestamp)%20ge%2000:01

"00:01" is preceded by %20, which is URL encoding for a space.

Decoded:
$filter=time(Timestamp) ge 00:01

**Comment by thebothead** [comment] 2015-03-24 13:27
Thanks for the reply...

The original query is correct from that I can tell from the specification.

URL Encoded Query:
$filter=time(Timestamp)%20ge%2000:01 

Decoded (%20 is a space):
$filter=time(Timestamp) ge 00:01 

The specification, as you have stated says:
hour   = ( "0" / "1" ) DIGIT
       / "2" ( "0" / "1" / "2" / "3" ) 

The allows for several combiniations, including the combiniation in my query.

As you can see the first line "( "0" / "1" ) DIGIT" allows for a 0 or 1 followed by any digit (0 through 9).  This accommodates hours 0 through 19.

The second line ""2" ( "0" / "1" / "2" / "3" )" allows for a 2 followed by 0, 1, 2, or 3.  This allows for hours 20 through 23.

Therefore I believe the query is correct and this is still an open issue.

**Comment by VikingsFan** [comment] 2015-03-25 01:28
reopen the issue,
@thebothead please try master branch or v5.5 beta, I think this is working now, the test case you can find in test\System.Web.OData.Test\OData\EnableQueryTests:

 {"?$filter=time(AbsoluteBirthDate) eq 01:02:03.0040000", "time"}

If you want to allow logical operators like 'ge', just set the AllowedLogicalOperators = AllowedLogicalOperators.All in EnableQuery Attribute.

**Comment by VikingsFan** [comment] 2015-04-02 01:35
@thebothead , as I said above, please help to confirm that the issue is resoled by WebAPI V5.5.

**Comment by VikingsFan** [comment] 2015-04-05 15:20
Close as #2 .

**Closed by VikingsFan** 2015-04-05 15:20 UTC
Labels: bug, Import From CodePlex, low
