### ISSUE TITLE
Some of my Get methods that work in Microsoft.AspNetCore.OData 7.4.1 result in 404 in 7.5.0

### ISSUE THREAD

**Issue by needo2** [OData/WebApi#2301] opened 2020-09-29 07:30 UTC
Works in Microsoft.AspNetCore.OData 7.4.1
Breaks in Microsoft.AspNetCore.OData 7.5.0

Get methods in my project defined as

    [EnableQuery]  
    public virtual async Task<IActionResult> Get()

Still work (200 + result)
These are for my directly queried entities

----

Get methods in my project that are defined as

    public Task<ListResult<TModel>> Get([FromQuery] TArgs args, ODataQueryOptions<TModel> queryOptions)

Don't work anymore (404, no exception message or anything)
These are for entities queried by stored procedure
ListResult contains paging information

----

Even if I'm doing something wrong without knowing, this still highlights a breaking change and it should be in the release notes as a breaking change.

Update: Replacing return type with `Task<IActionResult>` did NOT help

**Comment by henrikdahl8240** [comment] 2020-09-30 06:46
I cannot invoke even one of my Function definitions, all result in 404, Not Found. Now I am back at 7.4.1 and this works again. Has 7.5.0 really passed the test suite before being released?

**Comment by marabooy** [comment] 2020-09-30 11:58
@henrikdahl8240 this seems to be a regression in 7.5 on how the action selector handles some case. Glad to hear it is working in 7.4 as we work on a fix for this issue.

**Comment by habbes** [comment] 2020-10-05 08:37
I think the issue could be the `[FromQuery] TArgs args` not being recognized by the action selector as parameters bound to the query options. Let me investigate it.

**Comment by xuzhg** [comment] 2020-10-20 21:25
Merged at https://github.com/OData/WebApi/commit/dc77dce6ef16235c5f151592a6636e87b064efee

**Closed by xuzhg** 2020-10-20 21:25 UTC
Labels: P2, bug, regression
