### ISSUE TITLE
ASP.NET Core support?

### ISSUE THREAD

**Issue by akorchev** [OData/WebApi#1014] opened 2017-06-29 15:18 UTC
What is the status of this? There are [four unofficial packages in nuget](https://www.nuget.org/packages?q=Microsoft.AspNetCore.OData) and no clear info if official OData support for ASP.NET Core is coming soon or ever.

I see that the old vNext branch is deleted and there is a new one called maintenance-aspnetcore. Does any work regarding ASP.NET Core support happen in the master branch now? 

Please guys, don't keep us in the dark.

**Comment by joshbooker** [comment] 2017-06-30 00:59
+1 a statement of direction is in order after a rather lengthy slow time during transition of OData team. Thanks in advance.

**Comment by jan-gehlhaar** [comment] 2017-07-11 10:50
+1 on that from me as well. Got a customer that needs OData-Support and all we got currently got is ASP.NET Core. 
Rock - Me - Hard place
Thanks in advance!

**Comment by grahamehorner** [comment] 2017-07-13 19:17
+1 from me also

**Comment by earloc** [comment] 2017-07-15 09:53
same here! any updates highly appreciated!

**Comment by kennethalong** [comment] 2017-08-01 19:47
+1

**Comment by jaybockD** [comment] 2017-08-02 22:02
Ditto. Please confirm this is a priority. Thanks!

**Comment by mikepizzo** [comment] 2017-08-03 01:25
Yes, .NET Core support for WebAPI OData is a priority.  We have already done the work for .NET Core support in ODataLib, but support in WebAPI OData is a really big job due to extensive changes in ASP.NET.

Rather than maintain a separate branch for .NET Core, we are investing in adding .NET Core support to the WebAPI master branch.  We have done the refactoring necessary to add the ability to build .NET Core.

Sorry for the delay, and thanks for hanging with us.  As I say, it is a priority, it's just a lot of work.

Closing this as a duplicate of the dozens of other requests for .NET Core support in WebAPI OData.

**Closed by mikepizzo** 2017-08-03 01:25 UTC
