### ISSUE TITLE
Filter with embedded $count causes NotImplementedException

### ISSUE THREAD

**Issue by brjohnstmsft** [OData/WebApi#806] opened 2016-09-05 19:21 UTC
When a customer sends a query like `$filter=Tags/$count ge 1`, attempting to access the `FilterClause` property of `FilterQueryOption` results in a `NotImplementedException` being thrown. This is unexpected behavior -- no exception should be thrown.
### Assemblies affected

`Microsoft.AspNet.OData` 5.9.1. Possibly 6.x as well (I haven't tried it, but the underlying issue appears to still be in the code).
### Reproduce steps

Here is a full repro:

``` csharp
using System.ComponentModel.DataAnnotations;
using System.Net.Http;
using System.Web.OData;
using System.Web.OData.Builder;
using System.Web.OData.Query;
using System.Web.OData.Routing;
using Microsoft.OData.Edm;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ODataCountInFilterRepro
{
    [TestClass]
    public class FilterQueryOptionTests
    {
        private ODataQueryOptions _queryOptions;

        [TestInitialize]
        public void TestInitialize()
        {
            var modelBuilder = new ODataConventionModelBuilder();
            modelBuilder.EntitySet<TestEntityType>("entities");

            IEdmModel model = modelBuilder.GetEdmModel();

            const string BaseRequestUri = "http://localhost/entities";
            string requestUri = $"{BaseRequestUri}?$filter=Tags/$count ge 1";

            _queryOptions = CreateQueryOptions(model, requestUri);
        }

        [TestMethod]
        public void ExpectNoException()
        {
            Assert.IsNotNull(_queryOptions.Filter.FilterClause);
        }

        private static ODataQueryOptions CreateQueryOptions(IEdmModel model, string requestUri)
        {
            var request = new HttpRequestMessage(HttpMethod.Get, requestUri);
            var path = new ODataPath(new EntitySetPathSegment("entities"));
            var context = new ODataQueryContext(model, typeof(TestEntityType), path);
            var queryOptions = new ODataQueryOptions(context, request);
            return queryOptions;
        }

        private class TestEntityType
        {
            [Key]
            public string Id { get; set; }

            public string[] Tags { get; set; }
        }
    }
}
```
### Expected result

Accessing `FilterClause` should not throw an exception.
### Actual result

Accessing `FilterClause` throws `NotImplementedException`. The stack trace looks like this:

```
at Microsoft.OData.Core.UriParser.Visitors.QueryNodeVisitor`1.Visit(CountNode nodeIn)
   at Microsoft.OData.Core.UriParser.Semantic.CountNode.Accept[T](QueryNodeVisitor`1 visitor)
   at System.Web.OData.Query.ParameterAliasNodeTranslator.Visit(BinaryOperatorNode nodeIn)
   at Microsoft.OData.Core.UriParser.Semantic.BinaryOperatorNode.Accept[T](QueryNodeVisitor`1 visitor)
   at System.Web.OData.Query.FilterQueryOption.get_FilterClause()
```
### Additional details

The root cause appears to be that `ParameterAliasNodeTranslator` does not override all methods of its base class, `QueryNodeVisitor`. In particular, it does not override `Visit(CountNode)`.

**Comment by VikingsFan** [comment] 2016-09-06 00:35
I think you are asking this PR  https://github.com/OData/WebApi/pull/738 to be merge, we did't merge is because OData Lib didn't public the QueryNodeKind of CoundNode, so in my PR I always use as, and it's not consist with other code, we can merge this or wait a new release of ODataLib.

**Comment by brjohnstmsft** [comment] 2016-09-06 03:37
@VikingsFan I was unaware of that PR. My team found this issue because a customer sent our service a `$filter` expression with an embedded `$count` (which we do not support), and it caused a `NotImplementedException`, which caused our service to return an HTTP 500 response, which sent an alert to our on-call live site engineer.

It doesn't matter to us whether `$count` in `$filter` is supported or not -- our service does not expose it. Whether `$count` is supported or not, accessing `FilterClause` should *never* cause `NotImplementedException`.

From your description it sounds like the underlying issue is a mismatch of the set of supported `$filter` features between Web API OData and ODataLib. Such a mismatch should never occur. If I add the `Microsoft.AspNet.OData` package to my project, I expect it to work properly with all its dependencies, including ODataLib.

**Comment by xuzhg** [comment] 2016-09-06 07:06
The mismatch is not because that the latest ODL version (v6.15) supports $count segment in query option, while the latest WAO version (v5.9.1) doesn't support.  but because WAO can't support it owing that ODL hasn't supported it so far. 

As @VikingsFan said, we can merge the PR and let the customer to use nightly build, or wait for a new release of ODataLib.

**Comment by mikepizzo** [comment] 2017-05-30 21:38
Closing as duplicate of #194.

**Closed by mikepizzo** 2017-05-30 21:38 UTC
Labels: duplicate
