### ISSUE TITLE
[feature/netcore] ArgumentNullException: Value cannot be null. Parameter name: routeName

### ISSUE THREAD

**Issue by gordon-matt** [OData/WebApi#1175] opened 2017-12-22 01:12 UTC
Just updated the nuget package from alpha to beta and getting an error that wasn't there before:

**ArgumentNullException: Value cannot be null. Parameter name: routeName**

**Stack Trace:**

```
at Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.CreateRequestScope(HttpRequest request, String routeName)
   at Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.CreateRequestContainer(HttpRequest request, String routeName)
   at Microsoft.AspNet.OData.Extensions.HttpRequestExtensions.GetRoutingConventions(HttpRequest request)
   at Microsoft.AspNet.OData.Routing.ODataActionSelector.SelectCandidates(RouteContext context)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

Same demo project as you helped with before, which can be found here: [OData_Test](https://github.com/gordon-matt/OData_Test)

**Comment by robward-ms** [comment] 2017-12-22 08:13
@gordon-matt - Yep, it's a new issue that was caused by a last minute change. It occurs when a request is made on a non-OData route, which your project is configured to open (look in project properties, debug, app URL for the default URL). If you make a request against the configured OData endpoint, it should work as expected.

You can work around this issue by adding the following inside the UseMvc lambda, right below the call to MapODataServiceRoute(): 

routes.EnableDependencyInjection();

Where routes is the name of the IRouteBuilder lambda parameter.

**Comment by gordon-matt** [comment] 2017-12-22 08:45
OK that workaround does the trick, thanks. Is that going to be the "official" solution going forward or is it a temporary workaround, pending another fix?

**Comment by robward-ms** [comment] 2017-12-22 17:13
Temporary, I'll use this bug to track the fix.

**Comment by robward-ms** [comment] 2018-02-09 23:23
Fixed in Microsoft.AspNetCore.OData 7.0.0-Nightly201802092319.

**Comment by t03apt** [comment] 2018-02-10 10:07
I am getting the same error with 7.0.0-Nightly201802092319.
Small repo to reproduce it: https://github.com/t03apt/AspNetCoreOdataTest/tree/issues/argument-null-exception

**Comment by robward-ms** [comment] 2018-02-12 21:10
@t03apt - Not sure how it's best to handle this but the issue comes down to routing. YTour debug URI is set to:

`http://localhost:59656/api/orders`

But the defined OData route is:

`routeBuilder.MapODataServiceRoute("ODataRoute", "odata", builder.GetEdmModel());
`
So what happens in this case is that ASP.NET Routing is sending the request to your controller on a non-OData route, due to api vs odata in the URL. As it tries to bind ODataQueryOptions, it invokes the ODataQueryParameterBindingAttribute which looks for the model in the route container. Since it's not an OData route, there is no OData route container and you get the error.

There are two "work-arounds": 1.) Enable the non-OData route container, i.e. `EnableDependencyInjection()` or 2.) Use the odata route: `http://localhost:59656/odata/Orders`. Note that OData routes are case sensitive so it's Orders not orders.

I certainly think a better error message is in order here. However, I'm not convinced that another product change is required. Using ODataQueryOptions in a controller should be used on an OData route.

**Comment by robward-ms** [comment] 2018-02-13 00:19
@t03apt - #1237 improves the error messages you would see in your case, It would say:

> Cannot find the services container for the non-OData route. This can occur when using OData components on the non-OData route and is usually a configuration issue. Call EnableDependencyInjection() to enable OData components on non-OData routes. This may also occur when a request was mistakenly handled by the ASP.NET Core routing layer instead of the OData routing layer, for instance the URL does not include the OData route prefix configured via a call to MapODataServiceRoute().

**Comment by genusP** [comment] 2018-02-13 06:26
I test my code without EnableDependencyInjection(). OData routing work fine.

**Closed** 2018-05-01 21:14 UTC
Labels: P2, bug, feature/netcore, fixed
