### ISSUE TITLE
Selecting properties in a nested complex type does not work

### ISSUE THREAD

**Issue by ificator** [OData/WebApi#989] opened 2017-06-06 21:50 UTC
Say I have a model where a `Inner` complex type is nested within an `Outer` complex (or entity) type, so a request without a `$select` would return:

```
{
  "outerProperty1": "foo",
  "outerProperty2": "bah",
  "inner": {
    "innerProperty1": "foo",
    "innerProperty2": "bah"
  }
}
```

According to [the OData spec](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752360) I should be able to write a query like `...?$select=outerProperty1,inner/innerProperty2` and have it return:

```
{
  "outerProperty1": "foo",
  "inner": {
    "innerProperty2": "bah"
  }
}
```

However what we actually get is an `ODataException` with message:

```
A path within the select or expand query option is not supported.
```

### Assemblies affected
`System.Web.OData`

### Reproduce steps
1. Make a request against a resource with a complex type property, and include a `$select` statement that references just one of the properties within that complex type.

### Expected result
The request succeeds, and only the requested property from the complex type is returned.

### Actual result
The request fails. 

### Additional details
Issue #837 mentions this issue, but it seems prudent to track it specifically.

**Comment by xuzhg** [comment] 2017-06-08 20:22
BingAds has this requirement.

**Comment by daspek** [comment] 2017-06-09 01:00
Further, we need a complex syntax to represent this. Let's say we have this object:
```
{
  "outerProperty": "foo",
  "innerProperty": {
    "inner1": "foo",
    "inner2": "bah",
    "inner3": "baz",
    "inner4": "qux",
  }
}
```

We don't want to do `$select=innerProperty/inner1,innerProperty/inner2,innerProperty/inner3`.
Instead, it should look like nested expand syntax: `$select=innerProperty($select=inner1,inner2,inner3)`

**Comment by brjohnstmsft** [comment] 2017-07-22 05:03
@xuzhg Azure Search also has this requirement.

This seems to be a duplicate of https://github.com/OData/WebApi/issues/196 which as been open for a very long time. Any chance there will be traction on this soon?

FYI @robward-ms

**Comment by brjohnstmsft** [comment] 2017-07-26 19:25
Also related: https://github.com/OData/odata.net/issues/513

**Comment by ificator** [comment] 2017-08-23 17:22
It would also be nice if there was a capability of filtering collection properties that aren't navigations:

`$select=collectionProperty($filter=name%20eq%20'foo')`

**Comment by brjohnstmsft** [comment] 2018-05-31 01:12
@xuzhg I propose closing this issue since it is a duplicate of #196. If you agree, please close this.

**Closed** 2020-04-18 17:19 UTC
Labels: P2
