### ISSUE TITLE
ODataException thrown while parsing bound function template

### ISSUE THREAD

**Issue by hippiehunter** [OData/WebApi#1791] opened 2019-03-30 00:29 UTC
I'm seeing a failure during parsing of odata templates when driven by https://github.com/Microsoft/aspnet-api-versioning currently the parser produces operation segments and subsequently fails to build the parameter mapping when parsing something like the following "Availability/Default.FindAvailability(Region='{Region}',Unit='{Unit}',Member={Member},MemberArea={MemberArea},FunctionType='{FunctionType}',Adults={Adults},Children={Children},ReservationType={ReservationType},RateCode='{RateCode}')"

### Assemblies affected

Aspnetcore OData WebApi lib 7.1.0

### Reproduce steps

See added unit test in #1786 

### Expected result

No exception, template is parsed

### Actual result

Exception is thrown

**Comment by KanishManuja-MS** [comment] 2019-04-17 20:44
@hippiehunter Can you give more context on what you are trying to accomplish here? With the current syntax, Adults={Adults} is a valid template whereas Region=**'{Region}'** is not a template. Can you please let us know why some parameters are with single quotes?
Do you intend to have braces as part of the literal?

**Comment by hippiehunter** [comment] 2019-04-17 23:07
That's the syntax that aspnet-api-versioning is generating. I had assumed, possibly wrongly that it meant the data type was a string and needed to be quoted.

It seemed like the existing template parser code was expecting something like this for a literal but it just didn't quite match the parsed object types.

**Comment by mikepizzo** [comment] 2019-06-28 20:45
It appears from microsoft/aspnet-api-versioning#502 that this was an issue that will be addressed in the https://github.com/Microsoft/aspnet-api-versioning. Please confirm, and we will close this issue and the related PR (thanks @hippiehunter for the legwork on this!)

**Comment by commonsensesoftware** [comment] 2019-06-28 22:48
This is effectively a duplicate of #1786. The fix for microsoft/aspnet-api-versioning#502 will resolve both issues. Thanks.

**Comment by mikepizzo** [comment] 2019-07-03 17:12
Chris confirmed this is an issue in aspnet-api-versioning, and I believe has already fixed it, so closing this PR.  Thanks for your help getting this resolved!

**Closed by mikepizzo** 2019-07-03 17:12 UTC
Labels: follow up
