### ISSUE TITLE
OData query options are ignored in batch queries

### ISSUE THREAD

**Issue by osven** [OData/WebApi#1663] opened 2018-11-01 09:38 UTC
I have a ASP.NET OData service on top of a database. The service accepts queries with options, e.g.;

[...]/Well?$select=Id,Name,FieldName&$orderby=Name&$filter=ForecastId eq 123&$format=json

This request works as expected when it is sent as a plain GET request. But when the same request is sent as a $batch request the query options are ignored. It seems that the query string is not parsed when the GET request message is created from the batch request body.

### Assemblies affected

Microsoft.AspNetCore.App 2.1.4
Microsoft.AspNetCore.OData 7.0.1

### Reproduce steps

Request header:

Accept: multipart/mixed
Content-Type: multipart/mixed;boundary=batch_563f44e9-35b9-35ac-b21d-963524e695ab
Accept-Language: nb,en-GB;q=0.8,en;q=0.5,nn;q=0.3

Request body:

--batch_563f44e9-35b9-35ac-b21d-963524e695ab
Content-Type: application/http
Content-Transfer-Encoding:binary

GET [...]/Well?$select=Id,Name,FieldName&$orderby=Name&$filter=ForecastId eq 123&$format=json HTTP/1.1

--batch_563f44e9-35b9-35ac-b21d-963524e695ab

### Expected result

The response should contain only the specified columns, the returned rows should be limited as specified by the filter, and they should be ordered by **Name**.

### Actual result

The response contains all columns and all rows from the table, and the result is not sorted.

### Additional detail

When inspecting the **HttpContext.Request** object, I observe that the **QueryString** property is set correctly in both cases:

?$select=Id,Name,FieldName&$orderby=Name&$orderby=Name&$filter=ForecastId%20eq%20123&$format=json

 But in the batch case the **Query** collection is empty. In the non-batch case the **Query** collection contains the four options as expected.

Otherwise batching seems to work as expected.

**Comment by biaol-odata** [comment] 2018-11-02 17:41
@osven when inspecting the HttpContext.Request object for the Multipart-MIME batch request, are you on the client side or the $batch endpoint of the service side? Can you show us how the batch request was created in the client? The query options of the GET request should be processed along with the URI and I cannot think of any reason of them being dropped.

**Comment by osven** [comment] 2018-11-05 09:47
I'm inspecting the request on the service side.

The service is configuring the HTTP request pipeline with the standard `IApplicationBuilder.UseODataBatching` extension, followed by `UseMvc` that is calling `MapODataServiceRoute` on the route builder, passing a standard `DefaultODataBatchHandler` object.

On the client side the request is created from an HTML page using JavaScript and jQuery's ajax support:
```javascript
$.ajax({
   type: 'POST',
   contentType: 'multipart/mixed; boundary=' + boundaryText,
   url: this.serviceURL + '$batch',
   data: content,
   [...]
```

**Comment by biaol-odata** [comment] 2018-11-05 20:18
@osven Then looks like the request arriving at the $batch service endpoint does not have the query options in the request URL? The batch will be process without the query options in such case.

I would recommend examination of the request message on the wire from client side. If it is good, examine request message on the wire from service side, and subsequently upper layer processing before the request arrives at the $batch EP.

**Comment by osven** [comment] 2018-11-07 08:42
@biaol-odata I have debugged ```DefaultODataBatchHandler.ParseBatchRequestsAsync``` with the reproducible case I described above. The batch reader creates a new HTTP context object, and the ```CopyAbsoluteUrl``` extension method parses the uri and sets ```HttpRequest``` properties like ```QueryString``` and ```Path```. 

However, the ```Query``` property isn’t set and remains an empty collection. 

With my $batch case described above, the ```QueryString``` property is *?$select=Id,Name,FieldName&$orderby=Name&$filter=ForecastId eq 123&$format=json*

Then, on my GET controller action method: ```EnableQueryAttribute.CreateAndValidateQueryOptions``` creates an ```ODataQueryOptions``` object, which then creates a ```WebApiRequestMessage``` object. The implementation of the ```WebApiRequestMessage.QueryParameters``` property uses the empty ```HttpRequest.Query``` property:

```C#
public IDictionary<string, string> QueryParameters
{
    get
    {
        IDictionary<string, string> result = new Dictionary<string, string>();
        foreach (var pair in this.innerRequest.Query)
        {
            if (!result.ContainsKey(pair.Key))
            {
                result.Add(pair.Key, pair.Value);
            }
        }
        return result;
    }
}
```

Apparently, the default OData batch hander must fill the ```HttpRequest.Query``` collection when reading the query string from the uri.

**Comment by osven** [comment] 2018-11-21 07:12
Here is some additional information to clarify how to reproduce the problem.

My observation: If I call ```HttpRequest.Query.get()``` on the outer ($batch) HTTP POST request object before the batch handler starts generating request objects, the ```Query``` property of the inner (batch-generated) HTTP GET request will have no items when the ```QueryString``` property is set.
 
When I have this problem I see an indication in the inner request object; the ```request.QueryFeature.HttpRequestFeature``` property is an object of type ```Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection``` instead of the expected type ```Microsoft.AspNetCore.Http.Features.HttpRequestFeature```. 
 
It is strange, but this seems to happen if any code enquires the ```Query``` property of the original POST request before the batch handler creates the request object. It seems to be the ```DefaultHttpRequest.Query.get``` implementation that causes this.

The problem also happens when simply looking at the ```Query``` property in a watch window while debugging.
 
I need to enumerate the query options in a middleware that is invoked before the batch handler in the request pipeline. My current workaround is to check whether ```QueryString``` is empty before enumerating ```Query```. I also need to be careful when inspecting variables while debugging. 

``` C#
    if (context.Request.QueryString.HasValue)
    {
        var option = context.Request.Query.FirstOrDefault(v => v.Key == optionKey);
        [...]
    }
``` 

This works in my case. But it might be difficult to find a workaround in other cases.

**Comment by victorlazaro** [comment] 2019-04-25 18:00
I'm also facing the same issue, which is blocking development. Are there any updates?

**Comment by a99cl208** [comment] 2020-01-09 21:23
This is because if you have a query in your request and a middleware in your pipeline that set the Query property of the HttpContext before calling the batch middleware, therefore the QueryFeature is set on the httpcontext (the query property value in taken from the QueryFeature).

When executed, the batch middleware copy the existing features the child httpcontext that are created per change set request, so every request will have the same Query property than the batch request, which is not correct. Also, the enablequery filter uses the Query property to know if some filters should be applies.

You can try to do a /$batch?$top=1 and you will see that the $top will be applied to all you child queries.

As a workaround, set the UseODataBatching as the first method call in the pipeline configuration to be sure that no middleware will set the query feature, or add something like this juste before calling UseODataBatching to reset the query feature :

            app.Use(async (HttpContext httpContext, Func<Task> next) =>
            {
                httpContext.Features.Set<IQueryFeature>(null);
                await next();
            });

**Comment by gathogojr** [comment] 2023-09-06 12:04
@osven @victorlazaro @a99cl208 Please note that this issue cannot be reproduced. It could have been fixed in the intervening period.

I created a simple repro as follows:

### Library
Microsoft.AspNetCore.OData 8.2.0

### Data model
```csharp
namespace NS.Models
{
    public class Customer
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }

    public class EnterpriseCustomer : Customer
    {
        public decimal CreditLimit { get; set; }
    }
}
```

```csharp
using NS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Routing.Controllers;

namespace NS.Controllers
{
    public class CustomersController : ODataController
    {
        private readonly static List<Customer> customers = new List<Customer>
        {
            new Customer { Id = 1, Name = "Sue" },
            new EnterpriseCustomer { Id = 2, Name = "Joe", CreditLimit = 2300 }
        };

        [EnableQuery]
        public ActionResult<IEnumerable<Customer>> Get()
        {
            return customers;
        }

        [EnableQuery]
        public ActionResult<IEnumerable<EnterpriseCustomer>> GetFromEnterpriseCustomer()
        {
            return customers.OfType<EnterpriseCustomer>().ToList();
        }
    }
}
```

### Edm model and service configuration
```csharp
using NS.Models;
using Microsoft.AspNetCore.OData;
using Microsoft.AspNetCore.OData.Batch;
using Microsoft.OData.ModelBuilder;

var builder = WebApplication.CreateBuilder(args);

var modelBuilder = new ODataConventionModelBuilder();
modelBuilder.EntitySet<Customer>("Customers");

builder.Services.AddControllers().AddOData(
    options => options.EnableQueryFeatures().AddRouteComponents(
        model: modelBuilder.GetEdmModel(),
        batchHandler: new DefaultODataBatchHandler()));

var app = builder.Build();

app.UseODataBatching();
app.UseRouting();
app.UseEndpoints(endpoints => endpoints.MapControllers());

app.Run();
```

### Batch Request/Response

#### Request:
```http
POST http://localhost:5000/$batch
```

#### Request Body:
```
--batch_fcbd722c
Content-Type: application/http
Content-Transfer-Encoding: binary

GET http://localhost:5000/Customers?$select=Name HTTP/1.1

--batch_fcbd722c
Content-Type: application/http
Content-Transfer-Encoding: binary

GET http://localhost:5000/Customers?$filter=Name eq 'Joe' HTTP/1.1

--batch_fcbd722c
Content-Type: application/http
Content-Transfer-Encoding: binary

GET http://localhost:5000/Customers/NS.Models.EnterpriseCustomer?$select=CreditLimit HTTP/1.1

--batch_fcbd722c--
```

#### Reponse:
```
--batchresponse_eaa28b3a-9a69-418e-8279-34d8c0eba01f
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 200 OK
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
OData-Version: 4.0

{"@odata.context":"http://localhost:5000/$metadata#Customers(Name)","value":[{"Name":"Sue"},{"@odata.type":"#NS.Models.EnterpriseCustomer","Name":"Joe"}]}
--batchresponse_eaa28b3a-9a69-418e-8279-34d8c0eba01f
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 200 OK
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
OData-Version: 4.0

{"@odata.context":"http://localhost:5000/$metadata#Customers","value":[{"@odata.type":"#NS.Models.EnterpriseCustomer","Id":2,"Name":"Joe","CreditLimit":2300}]}
--batchresponse_eaa28b3a-9a69-418e-8279-34d8c0eba01f
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 200 OK
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8
OData-Version: 4.0

{"@odata.context":"http://localhost:5000/$metadata#Customers/NS.Models.EnterpriseCustomer(CreditLimit)","value":[{"CreditLimit":2300}]}
--batchresponse_eaa28b3a-9a69-418e-8279-34d8c0eba01f--
```

If you have reasons to believe the issue hasn't been adequately addressed, or scenarios I didn't take into consideration, feel free to reopen it.

**Closed by gathogojr** 2023-09-06 12:04 UTC
Labels: bug, P2
