### ISSUE TITLE
Put Delta Is Null in ODATA

### ISSUE THREAD

**Issue by gpm12gpm** [OData/WebApi#1067] opened 2017-09-01 09:27 UTC
Receiving null in below input parameter when sending navigation properties in the request body

 public async Task<IHttpActionResult> Put([FromODataUri] int key, Delta<Category> patch) {
         //patch is null 
        }
url:-http://localhost/xxxx.xxxx.Platform.API/referencedatamanagement/Categories(4342)
Below is the Request Body
{
"Name": "testdata",
"CategoryKeyID":4342,
"CategoryOwners":[
{
"OwnerKeyID":2
}
]
}

**Comment by fenixil** [comment] 2017-09-04 17:20
hi @gpm12gpm, which version of OData you use? 
I tried to reproduce the issue with 6.0.0, but all requests fail, because Delta is a generic. Once I changed it to `Delta<Category>` requests succeeded with non null argument.

Could you please provide OData package version and sources for `Category` and `CategoryOwner`, so that I'll try reproduce the issue?

Also kindly ask to use [markdown](https://guides.github.com/features/mastering-markdown/) to make comments more developers friendly :wink:

**Comment by gpm12gpm** [comment] 2017-09-05 07:08
hi @fenixil, Below are the packages, currently I am using in that perticular project.
<packages>
  <package id="Autofac" version="3.5.0" targetFramework="net452" />
  <package id="Autofac.WebApi2" version="4.0.1" targetFramework="net452" />
  <package id="CacheCow.Common" version="1.2.0" targetFramework="net452" />
  <package id="CacheCow.Server" version="1.2.0" targetFramework="net452" />
  <package id="Microsoft.AspNet.Cors" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.OData" version="5.9.0" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Cors" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.OData.Core" version="6.15.0" targetFramework="net452" />
  <package id="Microsoft.OData.Edm" version="6.15.0" targetFramework="net452" />
  <package id="Microsoft.Spatial" version="6.15.0" targetFramework="net452" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
</packages>

If I update the package to 6.0.0 or Beta 6.1.0 then I am getting the below error for this piece of code

`public async Task Put([FromODataUri] int key, Delta<Category> patch) {
//patch is null
patch.GetEntity();// Error in this line :- Method not found
}`

Also below line gives me error If I update to 6.0.0 or to Beta
var path = new System.Web.OData.Routing.ODataPath(new System.Web.OData.Routing.EntitySetPathSegment(name));

**Comment by gpm12gpm** [comment] 2017-09-05 07:09
hi @fenixil, Below are the packages, currently I am using in that perticular project.
```
<packages>
  <package id="Autofac" version="3.5.0" targetFramework="net452" />
  <package id="Autofac.WebApi2" version="4.0.1" targetFramework="net452" />
  <package id="CacheCow.Common" version="1.2.0" targetFramework="net452" />
  <package id="CacheCow.Server" version="1.2.0" targetFramework="net452" />
  <package id="Microsoft.AspNet.Cors" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.OData" version="5.9.0" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Cors" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.OData.Core" version="6.15.0" targetFramework="net452" />
  <package id="Microsoft.OData.Edm" version="6.15.0" targetFramework="net452" />
  <package id="Microsoft.Spatial" version="6.15.0" targetFramework="net452" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
</packages>
```

If I update the package to 6.0.0 or Beta 6.1.0 then I am getting the below error for this piece of code

`public async Task Put([FromODataUri] int key, Delta<Category> patch) {
//patch is null
patch.GetEntity();// Error in this line :- Method not found
}`

Also below line gives me error If I update to 6.0.0 or to Beta
var path = new System.Web.OData.Routing.ODataPath(new System.Web.OData.Routing.EntitySetPathSegment(name));

**Comment by gpm12gpm** [comment] 2017-09-05 08:52
Hi @fenixil  If I update to 6.0.0 my odata query option for get method also not working, if I mention anything like $filter or $expand for get. Below is the Category Model which automatically generated from EF Db first. Same thing works for Post but for not for Put

`    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.SrcCategorySysCodes = new HashSet<SrcCategorySysCode>();
            this.Children = new HashSet<Category>();
            this.BrandCategories = new HashSet<BrandCategory>();
            this.CategoryOwners = new HashSet<CategoryOwner>();
        }
    
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string VeryShortName { get; set; }
        public Nullable<int> ParentCategoryKeyID { get; set; }
        public string Description { get; set; }
        [Key]public int CategoryKeyID { get; set; }
        public Nullable<int> ApprovalStatusKeyID { get; set; }
        public Nullable<int> MasterCategoryKeyID { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SrcCategorySysCode> SrcCategorySysCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Children { get; set; }
        public virtual Category Parent { get; set; }
        public virtual ApprovalStatus ApprovalStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrandCategory> BrandCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryOwner> CategoryOwners { get; set; }
        public virtual Category Master { get; set; }
    }
`

**Comment by fenixil** [comment] 2017-09-06 20:37
@gpm12gpm, thanks for the details. I was able to reproduce the behavior locally and I think it is related to the navigation property `CategoryOwners`.

Put operation is used for full entity update, so you should not accept `Delta<T>` in it, but `T` instead. You may review method signatures in [Routing conventions](http://odata.github.io/WebApi/#03-02-built-in-routing-conventions) section of the docs.

If you want partially update the entity, you need to use PATCH method.
According to the [OData v4 spec](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398329) 
> 11.4.3 Update an Entity: The entity MUST NOT contain related entities as inline content. It MAY contain binding information for navigation properties. For single-valued navigation properties this replaces the relationship. 

Letting OData team to decide if any changes required to the sources, but looks like everything works according to the spec 👍.

**Comment by gpm12gpm** [comment] 2017-09-08 12:04
Hi @fenixil , Thank you for all your answer for this query. It will be help for me

**Comment by robward-ms** [comment] 2017-09-11 18:34
@fenixil - Thanks!
@gpm12gpm - If your issue is resolved, please close this GitHub issue.

**Closed** 2017-09-12 06:42 UTC
Labels: P4
