### ISSUE TITLE
If $top is not defined in query, return all rows

### ISSUE THREAD

**Issue by SMAH1** [OData/WebApi#2308] opened 2020-10-01 14:32 UTC
I use `asp.net core 3.1` and `Microsoft.AspNetCore.OData 7.5.0` with `NHibernate and FluentNHibernate`.

I config OData in _Startup.cs_ like this:

```
endpoint.MapControllers();
endpoint.EnableDependencyInjection();
endpoint
	.Select()
	.Expand(QueryOptionSetting.Disabled)
	.Filter()
	.OrderBy()
	.Count()
	.MaxTop(100)
	;
```

and use in controller like:

```
[HttpGet("/records"), EnableQuery, Authorize()]
public IQueryable<Record> GetRecords()
{
	return _deviceData.GetRecords();
}
```

and sevice like:

```
public interface IDeviceData
{
	...
	IQueryable<Record> GetRecords();
	...
}
```

Every thing is fine But I have one problem.
When user not define `$top` in query, return all rows and `MaxTop` not effect (!!!), but user define `$top` every thing OK (expected result).

### Assemblies affected

I Use only Microsoft.AspNetCore.OData 7.X

### Expected result

When user not define `$top` in query, `$top` set to equal `MaxTop` (In my sample, return 100 rows).

**Comment by SMAH1** [comment] 2020-10-02 09:57
This is [same problem](https://stackoverflow.com/questions/41961619/setting-a-default-page-size-for-a-webapi-2-odata-service). And solutions don't work.

**Comment by SMAH1** [comment] 2020-10-02 12:05
I solve it with Inherit from `EnableQueryAttribute`.
Add class `EnableQueryWithDefaultPageSizeAttribute`:

```
public class EnableQueryWithDefaultPageSizeAttribute : EnableQueryAttribute
{
	const int pageSizeDefault = 0;

	public override IQueryable ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
	{
		int? top = queryOptions?.Top?.Value;
		if (top == null)
		{
			return queryOptions.ApplyTo(queryable, new ODataQuerySettings { PageSize = this.PageSize == 0 ? pageSizeDefault : this.PageSize });
		}

		return queryOptions.ApplyTo(queryable); ;
	}
}
```

and change `EnableQuery` in Controller to `EnableQueryWithDefaultPageSize`.for example (above sample):

```
[HttpGet("/records"), EnableQueryWithDefaultPageSize, Authorize()]
public IQueryable<Record> GetRecords()
{
	return _deviceData.GetRecords();
}
```

**Note:** In above class support `PageSize` if it is defined.

**Comment by KenitoInc** [comment] 2020-10-06 13:17
@SMAH1 
`MaxTop` defines the max value of `$top` that a client can request. https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnet.odata.query.defaultquerysettings.maxtop
`MaxTop` only impacts the scenarios in which the request Uri contains `$top`. If the `$top` value exceeds the `MaxTop` value, you will get an error message.
`$top` allows us to get a subset of the results.
If you don't use `$top` in your request Uri, you will get all results, no matter the value you set in `MaxTop`.
Hope this helps.

**Comment by mikepizzo** [comment] 2020-10-06 16:48
Note: there is a subtle but important difference between the client-specified $top and the server returning the first page of results, along with a nextlink that can be used to fetch the next page of results.

$top is a client directive that says "i'm only interested in the first n records".  Once the service returns n records, it is done -- there is no next link.

A next link is returned by the service when there are more records to be returned than the service wants to return in a single response.  This can occur if the result is large and the client hasn't specified a $top, or if the result is large and the client has specified a $top greater than the number of rows the service is configured to return in a single response.  The next link both indicates that there are more records to return as well as providing the link to fetch the next page of records.

It would be a serious protocol violation to arbitrarily impose a $top by returning a subset of requested records without a nextlink. This is likely to result in the client believing they have all of the requested results when they have only received a partial result.

It sounds like you are interested in setting the maximum number of records returned by the service in a single page of results. This is done, as you discovered, through setting the PageSize.  However, setting PageSize does not need to be dependent up on $top -- the two are composable.  If the client-requested $top is greater than pagesize, then the service should return the first page of results, with a next link that fetches the next page of results *up to* the maximum specified in the client's $top.

For example, if there are 1000 rows but the client specifies $top=100 and the service has a pagesize of 50, the service would return the first 50 records with a nextLink to return a result containing the remaining 50 of the 100 requested rows with no nextlink.

**Comment by SMAH1** [comment] 2020-10-14 10:07
You mean: _PageSize_ is upper bound of _$top_.For example if `PageSize=100` and `$top=20`,return **20** rows.
But in my experience and #1853 when `PageSize=100 and $top=20` then return **100** rows.
In other words, **Ignore $top** when **PageSize is used**.

I agree with your scenario. **PageSize should be upper bound of $top** and **MaxTop should be upper bound of both**.

If we accept voice of @KenitoInc:
> If you don't use $top in your request Uri, you will get all results, no matter the value you set in MaxTop.

There should be a mechanism to limit the number of row count when $top is not defined..

**Comment by Ruslan878** [comment] 2020-10-14 10:18
> There should be a mechanism to limit the number of row count when $top is not defined..

That mechanism exists. You just need to set the needed PageSize in ODataQuerySettings. You can do that in different ways. One of them the next:

```c#
 public static PageResult<T> GetPageResult<T>(IQueryable<T> query, ODataQueryOptions<T> queryOptions) where T: class
        {
            IQueryable filteredList = queryOptions.ApplyTo(query, new ODataQuerySettings { PageSize = DefaultPageSize });
            ...
```

**Comment by SMAH1** [comment] 2020-10-14 14:38
I don't understand.
I define API like:

```
[HttpGet("/records"), EnableQuery, Authorize()]
public IQueryable<Record> GetRecords()
{
	return _deviceData.GetRecords();
}
```

Can I apply ODataQuerySettings?

**Note**: When define

```
[HttpGet("/records"), EnableQuery(PageSize = 100), Authorize()]
public IQueryable<Record> GetRecords()
{
	return _deviceData.GetRecords();
}
```

$top is ignored.

**Comment by KenitoInc** [comment] 2020-10-29 11:06
> I don't understand.
> I define API like:
> 
> ```
> [HttpGet("/records"), EnableQuery, Authorize()]
> public IQueryable<Record> GetRecords()
> {
> 	return _deviceData.GetRecords();
> }
> ```
> 
> Can I apply ODataQuerySettings?
> 
> **Note**: When define
> 
> ```
> [HttpGet("/records"), EnableQuery(PageSize = 100), Authorize()]
> public IQueryable<Record> GetRecords()
> {
> 	return _deviceData.GetRecords();
> }
> ```
> 
> $top is ignored.

@SMAH1 
I can't reproduce your issue. Everything works as expected.
Can you share a complete repro?
Can you also try using an In-Memory data store and see if it works correctly?

**Comment by SMAH1** [comment] 2020-11-04 15:58
Sample code for show bug is [here](https://github.com/SMAH1/DotnetcoreNHibernateSqliteOdataBug)

**Comment by KenitoInc** [comment] 2020-11-04 17:41
@SMAH1 Try using an In-Memory data store and see if it works correctly?

**Comment by SMAH1** [comment] 2020-11-05 11:10
> 
> 
> @SMAH1 Try using an In-Memory data store and see if it works correctly.

In-Memory works correctly. Why does not work correctly in nHibernate?

**Comment by KenitoInc** [comment] 2020-11-05 17:31
> > @SMAH1 Try using an In-Memory data store and see if it works correctly.
> 
> In-Memory works correctly. Why does not work correctly in nHibernate?

I am not really conversant with `nHibernate`. Also try using `EntityFramework` or `EntityFrameworkCore`.
If `EF` and `EF Core` works well, the problem is that `nHibernate` doesn't work well with `OData`.

**Comment by KenitoInc** [comment] 2021-06-11 05:57
Closing this issue for now.

**Closed by KenitoInc** 2021-06-11 05:57 UTC
Labels: follow up
