### ISSUE TITLE
filtering DateTime objects results with "bad array"

### ISSUE THREAD

**Issue by eyalkapah** [OData/WebApi#1516] opened 2018-07-05 06:56 UTC
trying to make a $filter query on DateTime object result with "Bad array" error.

`http://localhost:5002/odata/Rolls?$filter=StartTime gt 2018-02-02T00:00:00.00Z`

### Assemblies affected

Using .net core 2.1 (the latest)
and upgrade to the odata GA.

### Reproduce steps

just run it in postman.

### Expected result

get records where StartTime is bigger then 2018-02

### Actual result

Bad array

### Additional detail

I have just upgraded the server side to .NET Core 2.1 and the Odata GA

**Comment by biaol-odata** [comment] 2018-07-05 15:49
@eyalkapah To gather more information, can you please provide answers to the following questions:
- Does it work prior to upgrade? If yes, what was the WebApi version?
- Any further details for the error, such as service side stack trace?

**Comment by eyalkapah** [comment] 2018-07-08 05:41
@biaol-odata 
1. Prior to the upgrade it did work yes. I used the nightly builds (updating ~2 weeks)
I am using .net core 2.1.3 so i guess the latest web api (2.2?)

2. I'm not running it even from a C# code, but from postman... 
I attached a detailed stack trace for the command:

http://localhost:5002/odata/Rolls?$filter=StartTime gt 2018-02-02T00:00:00.00Z

[logger-all-2018-07-08.log](https://github.com/OData/WebApi/files/2173378/logger-all-2018-07-08.log)

**Comment by xuzhg** [comment] 2018-07-09 20:35
@eyalkapah 

It looks similar to https://github.com/OData/WebApi/issues/1473. Would you please take a look the comments in #1473. If it can't work, please share us your metadata?

**Comment by biaol-odata** [comment] 2018-07-09 20:46
@xuzhg #1473 is an issue of datatiemoffset / date conversion resulting in exception during parsing. Here the issue is BadArray, which appears that the parsing is OK, right? 
Anyway, @eyalkapah, if you are OK with using a different url, you can try date() as in #1473, or other functions such as time(), to see whether the error will go away.

**Comment by eyalkapah** [comment] 2018-07-10 09:38
using casting to date() solved the problem for now... thanks

**Comment by biaol-odata** [comment] 2018-07-10 18:06
Thanks for the updates. Closing this issue; feel free to re-open or submit new issues.

**Closed by biaol-odata** 2018-07-10 18:06 UTC
Labels: P3
