### ISSUE TITLE
Can't use MapODataServiceRoute more than once in WebApiConfig if using unbound functions

### ISSUE THREAD

**Issue by ImGonaRot** [OData/WebApi#1223] opened 2018-01-26 14:46 UTC
In the WebApiConfig if you have one MapODataServiceRoute with standard OData controllers and a unbound function, the service will work fine.
```cs
public static class WebApiConfig
{
    public static void Register(HttpConfiguration config)
    {
        // setup the odata service
        config.MapODataServiceRoute("odata", "odata", GetEdmModel());
    }

    private static IEdmModel GetEdmModel()
    {
        ODataConventionModelBuilder builder = new ODataConventionModelBuilder();

        // some entity
        builder.EntitySet<MainObject>(nameof(MainDbContext.MainObjects));
        // some unbound function
        builder.Function(nameof(MainObjectsController.GetSomeID)).Returns<int>();
        // build the edm
        var edmModel = builder.GetEdmModel();
            
        return edmModel;
    }
}

public class MainObjectsController : ODataController
{
    private MainDbContext db = new MainDbContext();

    public virtual IQueryable<MainObject> Get()
    {
        return db.Set<MainObject>();
    } 

    [HttpGet]        
    [ODataRoute("GetSomeID()")]
    public int GetSomeID()
    {
        return 1;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            db.Dispose();
        }
        base.Dispose(disposing);
    }
}
```
The above will work.
But if I add a second MapODataServiceRoute in WebApiConfig then I will receive the following error:

> The path template 'GetSomeID()' on the action 'GetSomeID' in controller 'MainObjects' is not a valid OData path template. Resource not found for the segment 'odata'.
Here is the code I changed to cause the error.
```cs
public static class WebApiConfig
{
    public static void Register(HttpConfiguration config)
    {
        // setup the odata service
        config.MapODataServiceRoute("odata", "odata", GetEdmModel());
        // new odata route
        config.MapODataServiceRoute("test", "test", GetTestEdmModel());
    }

    private static IEdmModel GetEdmModel()
    {
        ODataConventionModelBuilder builder = new ODataConventionModelBuilder();

        // some entity
        builder.EntitySet<MainObject>(nameof(MainDbContext.MainObjects));
        // some unbound function
        builder.Function(nameof(MainObjectsController.GetSomeID)).Returns<int>();
        // build the edm
        var edmModel = builder.GetEdmModel();
            
        return edmModel;
    }

    private static IEdmModel GetTestEdmModel()
    {
        ODataConventionModelBuilder builder = new ODataConventionModelBuilder();

        // some entity
        builder.EntitySet<TestObject>(nameof(TestDbContext.TestObjects));
        // build the edm
        var edmModel = builder.GetEdmModel();
            
        return edmModel;
    }
}
```

If I remove the unbound function from both the controller and the EDM builder, then it all works and I can get to the different objects using the two separate odata routes.

Seems that I am missing some route attribute on the unbound function.
I have tried 
`[ODataRoute("odata/GetSomeID()")]`
`[ODataRoute("odata/Default.GetSomeID()")]`
`[ODataRoute("Default.GetSomeID()")]`

I'm not sure how to get around this.

### Assemblies affected

System.Web.OData 6.1.0.10907

**Comment by RalfSeidel** [comment] 2018-04-24 09:07
Hi Alan,

this is duplicate of the issue #1390 

please see also: [https://social.msdn.microsoft.com/Forums/en-US/3ac517a7-99a4-4ecb-bb47-c1ec9c3a5f39/odata-4-unbound-functions-different-service-roots?forum=adodotnetdataservices](MSDN)

Ralf

**Comment by biaol-odata** [comment] 2018-05-11 18:14
@RalfSeidel #1390 is a PR, which provides a fix for issue #1286.
Looks like issues #1286 and #1223 are similar (both related to using multiple MapODataServiceRoute).

**Comment by biaol-odata** [comment] 2018-05-11 18:31
This issue should be fixed by PR #1390 now.

**Closed by biaol-odata** 2018-05-11 18:31 UTC
Labels: question

**Comment by biaol-odata** [comment] 2018-05-11 23:59
@ImGonaRot According to the description, it has no error for the first case ( single MapODataServiceRoute ), but the parenthesis when route attribute is specified ( [ODataRoute("GetSomeID()")] ) does seems unusual  to me. We will try to have a repo on WebApi v6.1, but can you confirm that [ODataRoute("GetSomeID")] still won't work for you? Thanks.

**Comment by popovanastas** [comment] 2018-05-14 09:44
@biaol-odata Hello, 
Both [ODataRoute("GetSomeID()")]  and [ODataRoute("GetSomeID")] works if only single MapODataServiceRoute is used and both are failing if multiple MapODataServiceRoute are used.

A workaround is to use custom AttrubuteRoutingConvention to separate the controllers per ServiceRoutes:

`public class MultipleServiceRoutesAttributeRoutingConvention : AttributeRoutingConvention
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultipleServiceRoutesAttributeRoutingConvention"/> class to handle bug in System.Web.OData lib version 6.1.0.
        /// https://github.com/OData/WebApi/issues/1223
        /// 
        /// Can't use MapODataServiceRoute more than once in WebApiConfig if using unbound functions
        /// </summary>
        /// <param name="routeName">The name of the route.</param>
        /// <param name="config">The System.Web.Http.HttpConfiguration to use for figuring out all the controllers to look for a match.</param>
        /// <param name="controllers">ODataController types that should be mappped by this MultipleServiceRoutesAttributeRoutingConvention instance.</param>
        public MultipleServiceRoutesAttributeRoutingConvention(string routeName, HttpConfiguration config, IEnumerable<Type> controllers) :
            base(routeName, config)
        {
            if (controllers == null)
                throw new ArgumentNullException(nameof(controllers));

            _controllers.AddRange(controllers);
        }

        public override bool ShouldMapController(HttpControllerDescriptor controller)
        {
            return _controllers.Contains(controller.ControllerType);
        }

        private readonly List<Type> _controllers = new List<Type> { typeof(MetadataController) };
    }`

And then passing a collection of controllers related to that particular ODataServiceRoute:

`builder
	.AddService<IEnumerable<IODataRoutingConvention>>(ServiceLifetime.Singleton, sp =>
		ODataRoutingConventionsFactory.CreateDefault(
			new MultipleServiceRoutesAttributeRoutingConvention(param.RouteName, config, HttpControllerTypeResolverHelper.GetControllerTypes(item.GetType().Assembly))
		)
	)`

The bug itself is situated in System.Web.OData.dll, somewhere in [those lines](https://github.com/OData/WebApi/blob/c5893e23ef18774dbaac855fadbcc7f6f22f612e/src/Microsoft.AspNet.OData/Routing/Conventions/AttributeRoutingConvention.cs#L270).

Anastas

**Comment by biaol-odata** [comment] 2018-05-14 17:28
@popovanastas Thanks for the info. Let's flag it as a bug first.

**Comment by popovanastas** [comment] 2018-05-14 19:17
@biaol-odata Basically an exception is thrown if particular ODataController has [ODataRoute("GetSomeID()")] attribute on some UnboundFunction and that controller is mapped to any additional ODataServiceRoute besides the one where we declared the Unbound function.

The exception message is the one @ImGonaRot mentioned.

> The path template 'GetSomeID()' on the action 'GetSomeID' in controller 'MainObjects' is not a valid OData path template. Resource not found for the segment 'odata'.

Regards,
Anastas
