### ISSUE TITLE
Upgrade from version 7.15.0 to 7.16.0 broken 

### ISSUE THREAD

**Issue by premiaware** [OData/WebApi#2784] opened 2023-05-25 12:44 UTC
Dear. 
I have update my WebApi App with OData 7.15.0 to 7.16.0 but it throw exception using controller 

I use this controller:

```csharp
public class baseGenericODataController : ODataController
{
    protected static ODataValidationSettings _validationSettings = new ODataValidationSettings() { **MaxExpansionDepth** = 4 };
    private GenericContext _db;

    public baseGenericODataController(GenericContext dbContext)
    {
        _db = dbContext;
    }

    public GenericContext db { get => Request.GetContext(); }

    protected override void Dispose(bool disposing)
    {
        _db.Dispose();
        base.Dispose(disposing);
    }

    [EnableQuery(AllowedQueryOptions = AllowedQueryOptions.All)]
    public IHttpActionResult Get(ODataQueryOptions<T> queryOptions)
    {
        //return TableForT();

        //string userId = User.Identity.Name;
            
        // validate the query.
        try
        {
            queryOptions.Validate(_validationSettings);
        }
        catch (ODataException ex)
        {
            return BadRequest(ex.Message);
        }
        
        return Ok<IEnumerable<T>>(TableForT().AsQueryable().AsNoTracking());
    }
}
```
If i remove
```csharp
protected static ODataValidationSettings _validationSettings = new ODataValidationSettings() { **MaxExpansionDepth** = 4 };
```
working fine.

Now i must rollback to previous release because .16 no work.

An error occurred while processing this request.

Inner Exception:
>> {"error":{"code":"","message":"The query specified in the URI is not valid. 'LevelsMaxLiteralExpansionDepth' should be less than or equal to 'MaxExpansionDepth'.","innererror":{"message":"'LevelsMaxLiteralExpansionDepth' should be less than or equal to 'MaxExpansionDepth'.","type":"Microsoft.OData.ODataException","stacktrace":"   in Microsoft.AspNet.OData.Query.Validators.SelectExpandQueryValidator.Validate(SelectExpandQueryOption selectExpandQueryOption, ODataValidationSettings validationSettings)\r\n   in Microsoft.AspNet.OData.Query.SelectExpandQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   in Microsoft.AspNet.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   in Microsoft.AspNet.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   in Microsoft.AspNet.OData.EnableQueryAttribute.ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions)\r\n   in Microsoft.AspNet.OData.EnableQueryAttribute.CreateAndValidateQueryOptions(HttpRequestMessage request, ODataQueryContext queryContext)\r\n   in Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)\r\n   in Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)"}}}
   at Microsoft.OData.Client.BaseAsyncResult.EndExecute[T](Object source, String method, IAsyncResult asyncResult)
   at Microsoft.OData.Client.QueryResult.EndExecuteQuery[TElement](Object source, String method, IAsyncResult asyncResult)
   at Microsoft.OData.Client.QueryResult.EndExecuteQuery[TElement](Object source, String method, IAsyncResult asyncResult)
   at Microsoft.OData.Client.DataServiceRequest.EndExecute[TElement](Object source, DataServiceContext context, String method, IAsyncResult asyncResult)
   at Microsoft.OData.Client.DataServiceQuery`1.EndExecute(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at AppData.Services.DataRepository.<>c__DisplayClass515_1.<<UtentiAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at AppData.Services.DataRepository.UtentiAsync(Int64 ID, Boolean CaricaDatiCompleti)

**Comment by gathogojr** [comment] 2023-06-02 18:57
Thank @premiaware for reporting this issue.
I'm going to assume the following:
- By **WebApi App with OData 7.15.0** you are implying `Microsoft.AspNetCore.OData 8.1.0-8.1.2` bundled with `Microsoft.OData.Core 7.15.0` as a dependency
- By **WebApi App with OData 7.16.0** you are implying `Microsoft.AspNetCore.OData 8.2.0` or higher bundled with `Microsoft.OData.Core 7.16.0` as a dependency

The reason for my assumptions being that there are no 7.15.0 or 7.16.0 versions of `Microsoft.AspNet.OData` or `Microsoft.AspNetCore.OData`

Your controller action implementation has both the `EnableQuery` attribute and the `ODataQueryOptions<T>` parameter.
The `EnableQuery` attribute won't reference or make use of the `ODataQueryOptions<T>` parameter on your controller action. Instead, it will internally create an instance of `ODataQueryOptions<T>` and then proceed to call the `ApplyTo` method of that instance.

 For the same reason, the `Validate` method call from the body of the controller action has no effect on the `EnableQuery` attribute. The `EnableQuery` attribute still has a `MaxExpansionDepth` of 2 (default). Having both the `EnableQuery` attribute and the `ODataQueryOptions<T>` is likely to cause unexpected and/or buggy behaviour - especially if you call the `ApplyTo` method of the `ODataQueryOptions<T>` parameter from the body of the controller action. Reason being that `EnableQuery` will also call `Validate` and `ApplyTo` on a different instance of `ODataQueryOptions<T>`.

Either use:
```csharp
protected static ODataValidationSettings validationSettings = new ODataValidationSettings
{
    MaxExpansionDepth = 4,
    AllowedQueryOptions = AllowedQueryOptions.All
};

public ActionResult Get(ODataQueryOptions<T> queryOptions)
{
    queryOptions.Validate(validationSettings);
    var result = queryOptions.ApplyTo(TableForT().AsQueryable());
    // ...
    return Ok(result);
}
```
Or
```csharp
[EnableQuery(AllowedQueryOptions = AllowedQueryOptions.All, MaxExpansionDepth = 4)]
public ActionResult Get()
{
	// ...
	return Ok(TableForT());
}
```

I couldn't reproduce the issue against either of the versions you referred to. If you continue observing the exception after taking into consideration the things I have mentioned above, kindly share a repro that I can look at. Alternatively, share exact steps to reproduce the issue.

**Comment by gathogojr** [comment] 2023-06-06 05:29
Hi @premiaware. Have you had a chance to review the response I shared above. Let me know if it helped in your situation

**Comment by gathogojr** [comment] 2023-06-07 11:33
I'll go ahead and close this issue. Feel free to reopen if my response doesn't adequately address it.

**Closed by gathogojr** 2023-06-07 11:33 UTC
Labels: bug, regression, P2

**Comment by premiaware** [comment] 2023-06-07 13:38
the only working solution is this:

[EnableQuery(AllowedQueryOptions = AllowedQueryOptions.All, MaxExpansionDepth = 4)]
public ActionResult Get()
{
	// ...
	return Ok(TableForT());
}

But it is a pity that it cannot be used as it was before, now I have to insert a constant in all controllers.
