### ISSUE TITLE
stackoverflow on HttpActionDescriptorExtensions.GetEdmModel

### ISSUE THREAD

**Issue by fernandolguevara** [OData/WebApi#320] opened 2015-04-29 20:51 UTC
When a OData query starts the library creates an IEdmModel 

EnableQuery.cs
...
model = actionDescriptor.GetEdmModel(elementClrType);
...

For Example
http://.../Customers?$top=10

then the main entity is added to the model with their properties.

BaseEntity.cs
public class BaseEntity {
    [NotMapped, JsonIgnore]
    public DbEntityEntry Entry { get; set; }
}

Customer.cs
public class Customer : BaseEntity {
   public string FirstName {get; set;}
   
   //SomeObj : BaseEntity
   public SomeObj {get;set}
}

if the entity has a ref. property for example DbEntityEntry the program ends with a StackOverFlowException

the exception happens in StructuralTypeConfiguration.cs

Name = ClrType.EdmName();

sorry about my english

**Comment by VikingsFan** [comment] 2015-06-10 07:01
@fernandolguevara Hi, I can't reproduce the bug, can you share more code? and you are using WebApi V3 or V4?

**Comment by xuzhg** [comment] 2016-06-02 03:12
Close it. please file a new issue if you have further concern. Thanks.

**Closed by xuzhg** 2016-06-02 03:12 UTC
Labels: 1 - Backlog, FollowUp
