### ISSUE TITLE
Asp.net web API 2.2 for Odata V4-$filter, $skip, $top, $orderby does not work inside $expand

### ISSUE THREAD

**Issue by LianwMS** [OData/WebApi#126] opened 2015-01-12 02:11 UTC
Hi  
  
Having an issue with Asp.net web API 2.2 for Odata V4(V 5.2.0-rtm-140611).  
  
I got a DB set Category which contains a group of UnionRanking, and below URL
works fine.  
  
UR:  

##  http://localhost:7272/Category?$expand=UnionRanking

    
    
    {
      "@odata.context":"http://localhost:7272/$metadata#Category","value":[
        {
          "Id":2,"Name":"\u6587\u5316","PrevailingRate":1.00,"ParentId":null,"Level":1,"UnionRanking":[
            {
              "CategoryId":2,"UnionId":"ed0c2df6-8136-4d1e-a697-43001786f0e3","PrevailingRate":1.00,"Rank":1
            },{
              "CategoryId":2,"UnionId":"575a2de5-61d8-4aa9-997b-609c8de67802","PrevailingRate":0.90,"Rank":2
            }
          ]
        },{
          "Id":3,"Name":"\u4e66\u7c4d","PrevailingRate":1.00,"ParentId":2,"Level":2,"UnionRanking":[
            
          ]
        },{
          "Id":4,"Name":"\u5f71\u89c6","PrevailingRate":1.00,"ParentId":2,"Level":2,"UnionRanking":[
            
          ]
        },{
          "Id":5,"Name":"\u5236\u9020","PrevailingRate":0.80,"ParentId":null,"Level":1,"UnionRanking":[
            
          ]
        },{
          "Id":6,"Name":"\u516c\u76ca","PrevailingRate":0.78,"ParentId":null,"Level":1,"UnionRanking":[
            
          ]
        }
      ]
    }
    

* * *

But if I tried [
http://localhost:7272/Category?$expand=UnionRanking($orderby=Rank) or
http://localhost:7272/Category?$expand=UnionRanking($orderby=Rank desc), the
order by inside expand does not work
](http://localhost:7272/Category?$expand=UnionRanking\($orderby=Rank\)

or http://localhost:7272/Category?$expand=UnionRanking\($orderby=Rank desc\),
the order by inside expand does not work) . Neither of $filter, $skip, $top.  
  
http://localhost:7272/Category?$expand=UnionRanking($top=1)  

    
    
    {
      "@odata.context":"http://localhost:7272/$metadata#Category","value":[
        {
          "Id":2,"Name":"\u6587\u5316","PrevailingRate":1.00,"ParentId":null,"Level":1,"UnionRanking":[
            {
              "CategoryId":2,"UnionId":"ed0c2df6-8136-4d1e-a697-43001786f0e3","PrevailingRate":1.00,"Rank":1
            },{
              "CategoryId":2,"UnionId":"575a2de5-61d8-4aa9-997b-609c8de67802","PrevailingRate":0.90,"Rank":2
            }
          ]
        },{
          "Id":3,"Name":"\u4e66\u7c4d","PrevailingRate":1.00,"ParentId":2,"Level":2,"UnionRanking":[
            
          ]
        },{
          "Id":4,"Name":"\u5f71\u89c6","PrevailingRate":1.00,"ParentId":2,"Level":2,"UnionRanking":[
            
          ]
        },{
          "Id":5,"Name":"\u5236\u9020","PrevailingRate":0.80,"ParentId":null,"Level":1,"UnionRanking":[
            
          ]
        },{
          "Id":6,"Name":"\u516c\u76ca","PrevailingRate":0.78,"ParentId":null,"Level":1,"UnionRanking":[
            
          ]
        }
      ]
    }

Please kind help.  
  
David  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 2037](http://aspnetwebstack.codeplex.com/workitem/2037)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jun 28, 2014 at 3:49 AM
**Reported by:**	huyq2002
**Updated on:**	Sep 25, 2014 at 2:08 AM
**Updated by:**	huyq2002

#### Binary Attachments

[error.png](http://aspnetwebstack.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=aspnetwebstack&WorkItemId=2037&FileAttachmentId=871195)

**Comment by LianwMS** [comment] 2015-01-12 02:11
On *2014-07-03 11:20:52 UTC*, **azhou** commented:

There are not supported yet in query option.

**Comment by LianwMS** [comment] 2015-01-12 02:11
On *2014-07-03 16:52:39 UTC*, **huyq2002** commented:

Thanks for the reply. Hope we have those features in the new release, otherwise the $expand funcion is limited in use. ( while $select already works fine.. )

**Comment by LianwMS** [comment] 2015-01-12 02:11
On *2014-09-25 09:08:55 UTC*, **huyq2002** commented:

The issue is already raised in issue no. 2046

Refer to below link,

https://aspnetwebstack.codeplex.com/workitem/2046

**Comment by ificator** [comment] 2015-02-06 17:05
Whatever is done to resolve this, please make sure that there is the capability to tell the framework to NOT apply its own sorting. My team is pulling orderby requests out of the appropriate clauses and having our database do the sorting for us, and as a result we DO NOT want our front-end to apply any additional sorting. We had to fight with the framework to make sure it didn't for direct $orderby, and I'd hate to have to go through that again for $orderby inside an $expand :)

**Comment by huyq2002** [comment] 2015-03-12 06:01
I was forced to write a lot of stored procedures and wrap them into Odata Action/Function to fix the issue.

**Comment by cherlyn** [comment] 2015-04-14 17:02
This should be the bug - not "feature" or "enhancement" because $orderby keyword just ignored in this case - no warnings or errors shown for such kind of URLs.

**Comment by esditm** [comment] 2015-05-22 12:10
:+1:

**Comment by VikingsFan** [comment] 2015-12-09 06:26
@ificator @huyq2002 @cherlyn @esditm 
I have a PR to get this feature work, would you pls take a look at it?
#569

**Comment by VikingsFan** [comment] 2015-12-23 02:59
Merged 3f568901da0a4d3b7d7aaecb29f66e5ce7e14429 PR #569

**Closed by VikingsFan** 2015-12-23 02:59 UTC
Labels: 2 - Active (in design), feature, Import From CodePlex

**Comment by manojkapoor** [comment] 2016-02-29 09:54
Do we have any plans to address this bug for the near release?

**Comment by nafnaf1000** [comment] 2016-02-29 20:26
It dos work.                .expand("tempPallets($select=id,time,cispShipmentIdActual,poId;$count=true;$orderby=id%20desc;$top=1)")
The issue is that it takes a long time.,
I qry went from 500ms to 3.2 sec

**Comment by xuzhg** [comment] 2016-03-01 01:17
@manojkapoor: It included in [v5.8](https://www.nuget.org/packages/Microsoft.AspNet.OData/5.8.0). Would you please take a look and try it?

@nafnaf1000:  Your query options do a lot of things. :) Does the performance (from 500ms to 3.2sec) work for you?

**Comment by nafnaf1000** [comment] 2016-03-01 15:34
@xuzhg 
not at all. I am looking for a better way.
the expand that I have is only on 25 rows of data so it relay slows it down.

each one of the $count $orderby $top adds a big slowness do it. I did not test witch one slows it down the most

**Comment by xuzhg** [comment] 2016-03-02 02:41
@nafnaf1000 would you please file a new issue for us to tracking on the performance?

**Comment by VikingsFan** [comment] 2016-08-08 03:13
@ificator I'm very excited to tell you we have a new feature to handle this scenario in the 6.0.0, night package are ready and document is [here](http://odata.github.io/WebApi/#04-26-modelbound-attribute), please have a try, any feedback is very appreciate.
