### ISSUE TITLE
Convention model builder: duplicate properties

### ISSUE THREAD

**Issue by Casimodo72** [OData/WebApi#355] opened 2015-05-21 15:02 UTC
Using ASP identity v2 (Microsoft.AspNet.Identity.EntityFramework v2), the ODataConventionModelBuilder creates duplicate properties.
I'm using "Microsoft.AspNet.OData" version="5.6.0-rc-150519-Nightly"

Scenario: 

I'm deriving all identity classes.
E.g. `public class Role : IdentityRole<Guid, UserRole>`

I'm using the ODataConventionModelBuilder to build the identity EDM types. Note that I also have to explicitely define the key property, otherwise OData will bark about the missing key on that type.

EntityTypeConfiguration<Role> role = builder.EntitySet<Role>("Roles").EntityType;
role.HasKey(p => p.Id); 

Calling builder.GetEdmModel(), results in two "Id" properties being created on that type.
```xml
<EntityType Name="Role" OpenType="true">
    <Key>
        <PropertyRef Name="Id" />
    </Key>
    <Property Name="Id" Type="Edm.Guid" Nullable="false" />
    <Property Name="Index" Type="Edm.Int32" />
    <Property Name="DisplayName" Type="Edm.String" Nullable="false" />
    <Property Name="Id" Type="Edm.Guid" Nullable="false" />
</EntityType>
```
Apparently building the other identity relationship types also produces duplicate properties as reported here: http://stackoverflow.com/questions/30316344/duplicate-columns-in-odata-metadata

Trying to query for my Roles results in the following error:

"error": {
     "code": "",
     "message": "An error has occurred.",
     "innererror": {
         "message": "The 'ObjectContent1 type failed to serialize the response body for content type 'application/json; odata.metadata=minimal'.",
         "type": "System.InvalidOperationException",
         "stacktrace": "",
         "internalexception": {
             "message": "Ein primitiver Wert wurde angegeben, es wurde jedoch ein Wert des nicht primitiven Typs '' erwartet.",
             "type": "Microsoft.OData.Core.ODataException",
             "stacktrace": "   
bei Microsoft.OData.Core.ValidationUtils.ValidateIsExpectedPrimitiveType(Object value,
		 IEdmPrimitiveTypeReference valuePrimitiveTypeReference, IEdmTypeReference expectedTypeReference, Boolean bypassValidation)
bei Microsoft.OData.Core.JsonLight.ODataJsonLightValueSerializer.WritePrimitiveValue(Object value, IEdmTypeReference expectedTypeReference)
bei Microsoft.OData.Core.JsonLight.ODataJsonLightPropertySerializer.WriteProperty(ODataProperty property, IEdmStructuredType owningType, 
		 Boolean isTopLevel, Boolean allowStreamProperty, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, 
		 ProjectedPropertiesAnnotation projectedProperties)
bei Microsoft.OData.Core.JsonLight.ODataJsonLightPropertySerializer.WriteProperties(IEdmStructuredType owningType, 
		 IEnumerable 1 properties, Boolean isComplexValue, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, 
		 ProjectedPropertiesAnnotation projectedProperties)
bei Microsoft.OData.Core.JsonLight.ODataJsonLightWriter.StartEntry(ODataEntry entry)
bei Microsoft.OData.Core.ODataWriterCore.<>c__DisplayClass14.<WriteStartEntryImplementation>b__12()
bei Microsoft.OData.Core.ODataWriterCore.InterceptException(Action action)
bei Microsoft.OData.Core.ODataWriterCore.WriteStartEntryImplementation(ODataEntry entry)
bei Microsoft.OData.Core.ODataWriterCore.WriteStart(ODataEntry entry)
bei System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.WriteEntry(Object graph, ODataWriter writer, ODataSerializerContext writeContext)
bei System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
bei System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteFeed(IEnumerable enumerable, IEdmTypeReference feedType, ODataWriter writer, ODataSerializerContext writeContext)
bei System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
bei System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
bei System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders)
bei System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content,
TransportContext transportContext, CancellationToken cancellationToken)
--- Ende der Stapel\u00fcberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel\u00f6st wurde ---
bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
bei System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"

Best regards,
Kasimier

**Comment by Casimodo72** [comment] 2015-05-22 12:55
- Is the ODataConventionModelBuilder intended to apply *additional* property configuration for an existing property (on the given type) explicitly at all?
Such a post-configuration would be great to have, if not being the most intuitively expected behavior.

- In MapEntityType, explicit navigation properties are effective, overwriting existing properties.

- In MapStructuralProperty, explicit structural properties are effective, but also existing properties. This creates duplicates.
- Shouldn't the builder throw an exception when duplicate properties are configured?

Currently, the conventions are applied in builder.GetEdmModel(). Before that the builder does not try to build models of the given type's properties. This means explicit configuration cannot "add" (e.g. configuring a property being key) to a property model because that model has not been built yet.

How to fix this? How about a staged build:

in ´´builder.EntitySet<Role>("Roles")´´:
1) build and add the property models
2) in case of navigation properties: don't try to resolve to the model, because it might not exist yet. Mark such properties for post-processing.
3) the user can now explicitly and intuitively "add" configurations to the property model
4) in builder.GetEdmModel(): resolve any missing references to models.

It this behavior breaks previous assumptions, then add an option to the builder in order to allow for such "overwrite" behavior.

Any thoughts out there?

**Comment by VikingsFan** [comment] 2015-05-27 03:08
Looks like duplicate reason is the same bug with #217 , but the fix may be a breaking change for us. But I think this is not a bug to block your scenario, first, if you have built the IdentityRole entityset, why declare Roles's Id is key, you should get Role through IdentityRole.
Or you just want the entityset is Roles, you can only build Role in convention model builder, and remove the explicit key declaration.

**Comment by Casimodo72** [comment] 2015-05-29 19:15
@VikingsFan, you are right. My example using the IdentityRole is *incorrect*. The keys need to be defined explicitely only on IdentityUserRole, IdentityUserClaim and IdentityUserLogin:
```c#
public static void Configure(ODataModelBuilder builder)
{
    EntityTypeConfiguration<Role> role = builder.EntitySet<Role>("Roles").EntityType;
    EntityTypeConfiguration<User> user = builder.EntitySet<User>("Users").EntityType;

    EntityTypeConfiguration<UserRole> userRole = builder.EntitySet<UserRole>("UserRoles").EntityType;
    userRole.HasKey(p => p.UserId);
    userRole.HasKey(p => p.RoleId);

    EntityTypeConfiguration<UserClaim> userClaims = builder.EntitySet<UserClaim>("UserClaims").EntityType;
    userClaims.HasKey(p => p.Id);

    EntityTypeConfiguration<UserLogin> userLogins = builder.EntitySet<UserLogin>("UserLogins").EntityType;
    userLogins.HasKey(p => p.UserId);
}
```
```xml
<EntityType Name="UserRole">
    <Key>
        <PropertyRef Name="UserId" />
        <PropertyRef Name="RoleId" />
    </Key>
    <Property Name="UserId" Type="Edm.Guid" Nullable="false" />
    <Property Name="RoleId" Type="Edm.Guid" Nullable="false" />
    <Property Name="UserId" Type="Edm.Guid" Nullable="false" />
    <Property Name="RoleId" Type="Edm.Guid" Nullable="false" />
</EntityType>
<EntityType Name="UserClaim">
    <Key>
        <PropertyRef Name="Id" />
    </Key>
    <Property Name="Id" Type="Edm.Int32" Nullable="false" />
    <Property Name="Id" Type="Edm.Int32" Nullable="false" />
</EntityType>
<EntityType Name="UserLogin">
    <Key>
        <PropertyRef Name="UserId" />
    </Key>
    <Property Name="UserId" Type="Edm.Guid" Nullable="false" />
    <Property Name="TenantId" Type="Edm.Guid" Nullable="false" />
    <Property Name="LoginProvider" Type="Edm.String" />
    <Property Name="ProviderKey" Type="Edm.String" />
    <Property Name="UserId" Type="Edm.Guid" Nullable="false" />
</EntityType>
```

Can you elaborate on: "the fix may be a breaking change for us". I interpret this as: "we have lots of duplicate properties defined on your side". In which case is it OK to have duplicate properties defined in the model? The current API related to this issue has the following behavior:
1) Explicit navigation property definitions overwrite conventions
2) Explicit structural property definitions do not overwrite conventions but create duplicates.
3) Creating duplicate property definitions does not throw an exception

Please, could you explain your scenario?

Regards,
Kasimier Buchcik

**Comment by Casimodo72** [comment] 2015-05-29 19:46
This *is* a blocker for us because we can't *expand* user roles.
E.g. here the request "http://localhost:26162/odata/Users/Ga.Lookup()?$expand=Roles" throws an exception in ODataLib in ValidateIsExpectedPrimitiveType.ValidationUtils
```{BadAmbiguousElementBinding : The name 'UserId' is ambiguous.}```

This is due to the duplicate property "UserId" on the IdentityUserRole.

Regards,
Kasimier Buchcik

**Comment by Casimodo72** [comment] 2015-05-29 21:29
This is *not* a blocker for me anymore. I just succeeded to work around this issue for the identity machinery: Since I derive all identity types and the relevant properties are virtual, I am able to override the key properties an set the [Key] attribute. Thus I don't need to explicitly define the keys thus can avoid the duplicate-property-bug.
E.g.:
```c#
public class UserLogin : MultitenantIdentityUserLogin<Guid, Guid>
{
	[Key]
	public override string LoginProvider
	{
	    get { return base.LoginProvider; }
	    set { base.LoginProvider = value; }
	}

	[Key]
	public override string ProviderKey
	{
	    get { return base.ProviderKey; }
	    set { base.ProviderKey = value; }
	}

	[Key]
	public override Guid UserId
	{
	    get { return base.UserId; }
	    set { base.UserId = value; }
	}
}
```
Regards,
Kasimier Buchcik

**Comment by VikingsFan** [comment] 2015-06-01 01:26
Sorry for the misunderstanding, the breaking change for us means change the public API in OData WebAPI, we don't encourage to use explicite define and convention together, that's why duplicate properties occur in your scenario, your work around seems cool for me, the #217 is open so close this issue.

**Comment by Casimodo72** [comment] 2015-06-01 12:44
@VikingsFan,
my work around may not apply to other scenarios. Any 3rd party types not giving us virtual key properties will not usable with the convention builder. This will be frustrating and create confusion, especially for newbies who can't or do not want to define all their models manually.

**Comment by VikingsFan** [comment] 2015-06-02 01:48
@Casimodo72 , pull request is very welcome, or I will help to follow up and fix this issue.

**Comment by Casimodo72** [comment] 2015-06-02 22:11
@VikingsFan, I chose the option "or I will help to follow up and fix this issue" :-) assuming you meant with that, that you'll fix this issue.
Thanks

**Comment by VikingsFan** [comment] 2015-06-08 06:11
@Casimodo72 Would you please help to review my pr #385 :)

**Comment by Casimodo72** [comment] 2015-06-11 14:57
@VikingsFan: Great! Thank you very much.
I had to learn today how to cherry-pick git commits before I could try out your fix.
The following configuration now works fine for me. No duplicates in the EDMX.

```c#
var role = builder.EntitySet<Role>("Roles").EntityType;
role.HasKey(p => p.Id);

var user = builder.EntitySet<User>("Users").EntityType;
user.HasKey(p => p.Id);

var userRole = builder.EntitySet<UserRole>("UserRoles").EntityType;
userRole.HasKey(p => new { p.UserId, p.RoleId });

var userClaims = builder.EntitySet<UserClaim>("UserClaims").EntityType;
userClaims.HasKey(p => p.Id);

var userLogins = builder.EntitySet<UserLogin>("UserLogins").EntityType;
userLogins.HasKey(p => new { p.LoginProvider, p.ProviderKey, p.UserId });
```

**Comment by Casimodo72** [comment] 2015-06-15 14:19
@VikingsFan, any estimation available as to when this fix will be merged in the master?

**Comment by xuzhg** [comment] 2015-06-17 02:18
Merged. @Casimodo72, can you try it out and let us know nay issue. Thanks

**Closed by xuzhg** 2015-06-17 02:18 UTC
Labels: bug, FollowUp

**Comment by Casimodo72** [comment] 2015-06-18 16:30
@xuzhg, I already used it for a week. No problems on my side - but my side is tiny.
Good to have it officially! Thanks
