### ISSUE TITLE
Any plan for .net core 3.0.0?

### ISSUE THREAD

**Issue by albertwoo** [OData/WebApi#1939] opened 2019-10-28 07:28 UTC
I find that the latest version only support Microsoft.AspNetCore.Mvc.Core (>= 2.0.0 && < 3.0.0). But .net core 3.0.0 is already release for a while, so is any time schedule to support that?

**Comment by NetTecture** [comment] 2019-10-28 19:28
Have a look at https://github.com/OData/WebApi/issues/1748

**Comment by mikepizzo** [comment] 2019-10-28 19:49
Closing as a duplicate of #1748. Short answer: yes, support for .NET Core 3.0 is a top priority and we are working to have a solution by the end of the year.

**Closed by mikepizzo** 2019-10-28 19:49 UTC
