### ISSUE TITLE
An incompatible primitive type 'Edm.Int32[Nullable=False]' was found for an item that was expected to be of type 'Edm.String[Nullable=True]

### ISSUE THREAD

**Issue by Inx51** [OData/WebApi#855] opened 2016-11-20 17:35 UTC
Hi!

I have created a quite basic Entity Framework model and bound this to the WebAPI OData-framework.
However..
For some reason when I run the following query:
http://localhost:23486/odata/Containers/?$filter=Name%20eq%20%27Products%27&$expand=Items($expand=Values($expand=StringValue,IntValue,BoolValue))

I end up with the following error/stack-trace:
{
error: {
code: "",
message: "An error has occurred.",
innererror: {
message: "The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; odata.metadata=minimal'.",
type: "System.InvalidOperationException",
stacktrace: "",
internalexception: {
message: "An incompatible primitive type 'Edm.Int32[Nullable=False]' was found for an item that was expected to be of type 'Edm.String[Nullable=True]'.",
type: "Microsoft.OData.ODataException",
stacktrace: " at Microsoft.OData.ValidationUtils.ValidateMetadataPrimitiveType(IEdmTypeReference expectedTypeReference, IEdmTypeReference typeReferenceFromValue) at Microsoft.OData.ValidationUtils.ValidateIsExpectedPrimitiveType(Object value, IEdmPrimitiveTypeReference valuePrimitiveTypeReference, IEdmTypeReference expectedTypeReference) at Microsoft.OData.WriterValidator.ValidateIsExpectedPrimitiveType(Object value, IEdmPrimitiveTypeReference valuePrimitiveTypeReference, IEdmTypeReference expectedTypeReference) at Microsoft.OData.JsonLight.ODataJsonLightValueSerializer.WritePrimitiveValue(Object value, IEdmTypeReference actualTypeReference, IEdmTypeReference expectedTypeReference) at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WritePrimitiveProperty(ODataPrimitiveValue primitiveValue, Boolean isOpenPropertyType) at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WriteProperty(ODataProperty property, IEdmStructuredType owningType, Boolean isTopLevel, Boolean allowStreamProperty, IDuplicatePropertyNameChecker duplicatePropertyNameChecker) at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WriteProperties(IEdmStructuredType owningType, IEnumerable`1 properties, Boolean isComplexValue, IDuplicatePropertyNameChecker duplicatePropertyNameChecker) at Microsoft.OData.JsonLight.ODataJsonLightWriter.StartResource(ODataResource resource) at Microsoft.OData.ODataWriterCore.<>c__DisplayClass14.<WriteStartResourceImplementation>b__12() at Microsoft.OData.ODataWriterCore.InterceptException(Action action) at Microsoft.OData.ODataWriterCore.WriteStartResourceImplementation(ODataResource resource) at Microsoft.OData.ODataWriterCore.WriteStart(ODataResource resource) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteComplexAndExpandedNavigationProperty(IEdmProperty edmProperty, SelectExpandClause selectExpandClause, ResourceContext resourceContext, ODataWriter writer) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteExpandedNavigationProperties(IDictionary`2 navigationPropertiesToExpand, ResourceContext resourceContext, ODataWriter writer) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteComplexAndExpandedNavigationProperty(IEdmProperty edmProperty, SelectExpandClause selectExpandClause, ResourceContext resourceContext, ODataWriter writer) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteExpandedNavigationProperties(IDictionary`2 navigationPropertiesToExpand, ResourceContext resourceContext, ODataWriter writer) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteComplexAndExpandedNavigationProperty(IEdmProperty edmProperty, SelectExpandClause selectExpandClause, ResourceContext resourceContext, ODataWriter writer) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteExpandedNavigationProperties(IDictionary`2 navigationPropertiesToExpand, ResourceContext resourceContext, ODataWriter writer) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType) at System.Web.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext) at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders) at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"
}
}
}
}

However.. if I change this:
http://localhost:23486/odata/Containers/?$filter=Name%20eq%20%27Products%27&$expand=Items($expand=Values($expand=StringValue,IntValue,BoolValue))
to this:
http://localhost:23486/odata/Containers/?$filter=Name%20eq%20%27Products%27&$expand=Items($expand=Values($expand=StringValue,BoolValue))
it all works just fine..
and the strange thing is that it all works just fine when doing this query as well:
http://localhost:23486/odata/Containers/?$filter=Name%20eq%20%27Products%27&$expand=Items($expand=Values($expand=IntValue,BoolValue))
So its the combination of StringValue and IntValue that throws the exception for some reason that I can't really understand why..

Here is my $metadata if thats for any kind of help:

`<?xml version="1.0" encoding="utf-8"?><edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx"><edmx:DataServices><Schema Namespace="Garnet.Data.Entities" xmlns="http://docs.oasis-open.org/odata/ns/edm"><EntityType Name="ContainerEntity"><Key><PropertyRef Name="Id" /></Key><Property Name="Name" Type="Edm.String" /><Property Name="Id" Type="Edm.Int32" Nullable="false" /><Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" /><NavigationProperty Name="Properties" Type="Collection(Garnet.Data.Entities.PropertyEntity)" /><NavigationProperty Name="Items" Type="Collection(Garnet.Data.Entities.ItemEntity)" /><NavigationProperty Name="Relationships" Type="Collection(Garnet.Data.Entities.ContainerRelationshipEntity)" /></EntityType><EntityType Name="ItemEntity"><Key><PropertyRef Name="Id" /></Key><Property Name="ContainerId" Type="Edm.Int32" Nullable="false" /><Property Name="Id" Type="Edm.Int32" Nullable="false" /><Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" /><NavigationProperty Name="Container" Type="Garnet.Data.Entities.ContainerEntity" /><NavigationProperty Name="Values" Type="Collection(Garnet.Data.Entities.PropertyValueEntity)" /></EntityType><EntityType Name="PropertyEntity"><Key><PropertyRef Name="Id" /></Key><Property Name="Name" Type="Edm.String" /><Property Name="Type" Type="Garnet.Data.Enums.TypeOfValue" Nullable="false" /><Property Name="ContainerId" Type="Edm.Int32" Nullable="false" /><Property Name="Id" Type="Edm.Int32" Nullable="false" /><Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" /><NavigationProperty Name="Container" Type="Garnet.Data.Entities.ContainerEntity" /><NavigationProperty Name="ForeignRelationships" Type="Collection(Garnet.Data.Entities.ContainerRelationshipEntity)" /><NavigationProperty Name="PrimaryRelationships" Type="Collection(Garnet.Data.Entities.ContainerRelationshipEntity)" /></EntityType><EntityType Name="PropertyValueEntity"><Key><PropertyRef Name="Id" /></Key><Property Name="IntValueId" Type="Edm.Int32" /><Property Name="StringValueId" Type="Edm.Int32" /><Property Name="BoolValueId" Type="Edm.Int32" /><Property Name="DoubleValueId" Type="Edm.Int32" /><Property Name="PropertyId" Type="Edm.Int32" /><Property Name="ItemId" Type="Edm.Int32" /><Property Name="Id" Type="Edm.Int32" Nullable="false" /><Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" /><NavigationProperty Name="IntValue" Type="Garnet.Data.Entities.Values.IntValueEntity" /><NavigationProperty Name="StringValue" Type="Garnet.Data.Entities.Values.StringValueEntity" /><NavigationProperty Name="BoolValue" Type="Garnet.Data.Entities.Values.BoolValueEntity" /><NavigationProperty Name="DoubleValue" Type="Garnet.Data.Entities.Values.DoubleValueEntity" /><NavigationProperty Name="Property" Type="Garnet.Data.Entities.PropertyEntity" /><NavigationProperty Name="Item" Type="Garnet.Data.Entities.ItemEntity" /></EntityType><EntityType Name="ContainerRelationshipEntity"><Key><PropertyRef Name="Id" /></Key><Property Name="PrimaryId" Type="Edm.Int32" Nullable="false" /><Property Name="ForeignId" Type="Edm.Int32" Nullable="false" /><Property Name="Id" Type="Edm.Int32" Nullable="false" /><Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" /><NavigationProperty Name="Primary" Type="Garnet.Data.Entities.PropertyEntity" /><NavigationProperty Name="Foreign" Type="Garnet.Data.Entities.PropertyEntity" /></EntityType></Schema><Schema Namespace="Garnet.Data.Entities.Values" xmlns="http://docs.oasis-open.org/odata/ns/edm"><EntityType Name="BoolValueEntity"><Key><PropertyRef Name="Id" /></Key><Property Name="DataValue" Type="Edm.Boolean" /><Property Name="PropertyValueId" Type="Edm.Int32" Nullable="false" /><Property Name="Id" Type="Edm.Int32" Nullable="false" /><Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" /><NavigationProperty Name="PropertyValue" Type="Garnet.Data.Entities.PropertyValueEntity" /></EntityType><EntityType Name="DoubleValueEntity"><Key><PropertyRef Name="Id" /></Key><Property Name="DataValue" Type="Edm.Double" /><Property Name="PropertyValueId" Type="Edm.Int32" Nullable="false" /><Property Name="Id" Type="Edm.Int32" Nullable="false" /><Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" /><NavigationProperty Name="PropertyValue" Type="Garnet.Data.Entities.PropertyValueEntity" /></EntityType><EntityType Name="IntValueEntity"><Key><PropertyRef Name="Id" /></Key><Property Name="DataValue" Type="Edm.Int32" /><Property Name="PropertyValueId" Type="Edm.Int32" Nullable="false" /><Property Name="Id" Type="Edm.Int32" Nullable="false" /><Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" /><NavigationProperty Name="PropertyValue" Type="Garnet.Data.Entities.PropertyValueEntity" /></EntityType><EntityType Name="StringValueEntity"><Key><PropertyRef Name="Id" /></Key><Property Name="DataValue" Type="Edm.String" /><Property Name="PropertyValueId" Type="Edm.Int32" Nullable="false" /><Property Name="Id" Type="Edm.Int32" Nullable="false" /><Property Name="Created" Type="Edm.DateTimeOffset" Nullable="false" /><NavigationProperty Name="PropertyValue" Type="Garnet.Data.Entities.PropertyValueEntity" /></EntityType></Schema><Schema Namespace="Garnet.Data.Enums" xmlns="http://docs.oasis-open.org/odata/ns/edm"><EnumType Name="TypeOfValue"><Member Name="Int" Value="0" /><Member Name="String" Value="1" /><Member Name="Double" Value="2" /><Member Name="Bool" Value="3" /><Member Name="Null" Value="4" /></EnumType></Schema><Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm"><EntityContainer Name="Container"><EntitySet Name="Containers" EntityType="Garnet.Data.Entities.ContainerEntity"><NavigationPropertyBinding Path="Properties" Target="Properties" /><NavigationPropertyBinding Path="Items" Target="Items" /><NavigationPropertyBinding Path="Relationships" Target="ContainerRelationships" /></EntitySet><EntitySet Name="Items" EntityType="Garnet.Data.Entities.ItemEntity"><NavigationPropertyBinding Path="Container" Target="Containers" /><NavigationPropertyBinding Path="Values" Target="PropertyValues" /></EntitySet><EntitySet Name="Properties" EntityType="Garnet.Data.Entities.PropertyEntity"><NavigationPropertyBinding Path="Container" Target="Containers" /><NavigationPropertyBinding Path="ForeignRelationships" Target="ContainerRelationships" /><NavigationPropertyBinding Path="PrimaryRelationships" Target="ContainerRelationships" /></EntitySet><EntitySet Name="PropertyValues" EntityType="Garnet.Data.Entities.PropertyValueEntity"><NavigationPropertyBinding Path="IntValue" Target="IntValues" /><NavigationPropertyBinding Path="StringValue" Target="StringValues" /><NavigationPropertyBinding Path="BoolValue" Target="BoolBalues" /><NavigationPropertyBinding Path="DoubleValue" Target="DoubleValues" /><NavigationPropertyBinding Path="Property" Target="Properties" /><NavigationPropertyBinding Path="Item" Target="Items" /></EntitySet><EntitySet Name="ContainerRelationships" EntityType="Garnet.Data.Entities.ContainerRelationshipEntity"><NavigationPropertyBinding Path="Primary" Target="Properties" /><NavigationPropertyBinding Path="Foreign" Target="Properties" /></EntitySet><EntitySet Name="BoolBalues" EntityType="Garnet.Data.Entities.Values.BoolValueEntity"><NavigationPropertyBinding Path="PropertyValue" Target="PropertyValues" /></EntitySet><EntitySet Name="DoubleValues" EntityType="Garnet.Data.Entities.Values.DoubleValueEntity"><NavigationPropertyBinding Path="PropertyValue" Target="PropertyValues" /></EntitySet><EntitySet Name="IntValues" EntityType="Garnet.Data.Entities.Values.IntValueEntity"><NavigationPropertyBinding Path="PropertyValue" Target="PropertyValues" /></EntitySet><EntitySet Name="StringValues" EntityType="Garnet.Data.Entities.Values.StringValueEntity"><NavigationPropertyBinding Path="PropertyValue" Target="PropertyValues" /></EntitySet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>`

The same things happens if I try to expand the DoubleValue as well:
http://localhost:23486/odata/Containers/?$filter=Name%20eq%20%27Products%27&$expand=Items($expand=Values($expand=DoubleValue,StringValue,BoolValue))
And also if I try to expand both DoubleValue and IntValue but remove the StringValue:
http://localhost:23486/odata/Containers/?$filter=Name%20eq%20%27Products%27&$expand=Items($expand=Values($expand=DoubleValue,IntValue,BoolValue))

any ideas to why I get this error in some cases?

The packages I have installed that are related to OData are:
```
  <package id="Microsoft.OData.Core" version="7.0.0" targetFramework="net46" />
  <package id="Microsoft.OData.Edm" version="7.0.0" targetFramework="net46" />
  <package id="Microsoft.AspNet.OData" version="6.0.0" targetFramework="net46" />
```

Thanks in advance!

**Comment by xuzhg** [comment] 2016-11-21 03:28
I can repro it at: https://github.com/xuzhg/WebApiSample/tree/master/vNext/WebApiBugFix

**Comment by LaylaLiu** [comment] 2016-11-21 07:05
@Inx51 This is an OData Issue. One workaround is to use different names for the DataValue properties in different types.

**Comment by Inx51** [comment] 2016-11-21 07:58
@LaylaLiu
Ah ok, I guess I might be able to use that as a workaround for now.. however its not a solid fix since all my Value-types are implementing the same interface which takes a generic argument för the type of the DataValue-property.. this workaround sort of breaks my currently implementation... So if there is any chance to get this property resolved then that would be great!
Is there any other issue-tracker where I should report this bug? I figured since you mentioned that this is related to OData and not OData/WebApi i guess.

Br,
inx

**Comment by Inx51** [comment] 2016-11-21 10:02
Can confirm that the workaround LaylaLiu mentioned works.. however.. as mentioned.. this should most likely not be considered a fix..

**Comment by LaylaLiu** [comment] 2016-11-23 02:10
@Inx51, You are right, this is a workaround, not a bug fix. 
BTW, xuzhg has opened a reference issue https://github.com/OData/odata.net/issues/724

**Comment by Inx51** [comment] 2016-11-23 07:33
Awesome! Thanks!

**Comment by tyrius02** [comment] 2017-01-10 17:39
Issue OData/odata.net#724 is a duplicate of OData/odata.net#706. The latter contains a bit more detail.

**Comment by biaol-odata** [comment] 2017-05-31 20:56
Close as duplicated to [OData/odata.net#706](https://github.com/OData/odata.net/issues/706)

**Closed by biaol-odata** 2017-05-31 20:56 UTC
Labels: duplicate
