### ISSUE TITLE
$filter on a sub entity field with not nullable numeric type doesn't work

### ISSUE THREAD

**Issue by magneticcore** [OData/WebApi#2371] opened 2020-11-26 07:40 UTC
It is impossible, during a GET, to use $filter to filter on a sub entity field which its type is not nullable, odata returning an exception:
$filter=entity/id eq 20 (id field: int, not null)

### Assemblies affected
Microsoft.AspNetCore.OData v7.5.2, v8.0.0-preview2
Microsoft.EntityFrameworkCore v5.0.0
AutoMapper 10.1.1

### Reproduce steps
PersonAddress is a class that contains Person field, Person being also a class. Both contain several fields, including id (int, not nullable).

Example of url that raises an exception:
http://localhost/api/personaddresses/?$expand=Person&$filter=Person/Id%20eq%2020

### Expected result
Must return a PersonAddress collection whose Person.Id field is equal to 20

### Actual result
The following exception is raised:
InvalidOperationException: The binary operator Equal is not defined for the types 'System.Nullable`1[System.Int32]' and 'System.Int32'

### Additional detail

All work correctly if the field type of the sub entity for the filtering is string or nullable numeric (int, nullable; double, nullable, etc.)

Examples of url that work:
http://localhost/api/personaddresses/?$expand=Person&$filter=Person/Age%20eq%2020 (Age field: int, nullable)
http://localhost/api/personaddresses?$filter=Person/FirstName%20eq%20%27Daniel%27 (FirstName field: string)

**Comment by ElizabethOkerio** [comment] 2020-12-01 13:43
@magneticcore  can you provide a simple repro for this issue so we can dig deeper. Am not able to reproduce this issue using the assemblies you mentioned above.

**Comment by ElizabethOkerio** [comment] 2020-12-04 06:22
@magneticcore Here is a simple repro of the issue that I tried and I was able to filter on a sub entity. https://github.com/ElizabethOkerio/WebApplicationCoreOdata

If you try this URL: https://localhost:44353/odata/Books?$expand=Press&$filter=Press/Id%20eq%202 you'll get a result.

**Comment by magneticcore** [comment] 2021-03-04 15:26
@ElizabethOkerio: I tested your project and yes, it is not a problem of OData, but of Automapper. I will put a link here to the Automapper issue

**Comment by KenitoInc** [comment] 2022-05-18 11:26
Closing this since it's not an OData issue

**Closed by KenitoInc** 2022-05-18 11:26 UTC
Labels: follow up
