### ISSUE TITLE
$filter by $top 1 record of an $expanded collection

### ISSUE THREAD

**Issue by robinmaple** [OData/WebApi#967] opened 2017-04-18 21:00 UTC
Hi,

Below Odata query will return the latest record of $expand StatusHistories, and it's working fine. I would like to further filter the record with StatusHistories/Status not 'Complete'. If adding " and StatusHistories/Status ne 'Complete' " to the end of the query, it will raise error "The parent value for a property access of a property 'Status' is not a single value. Property access can only be applied to a single value.". Is there a way to filter by the top 1 record selected? Thanks!

Host/odata/WorkOrders?$select=Id, Number, Request, Tag&$orderby=Priority desc, Id desc&$expand=Labors, StatusHistories($orderby=Id desc;$top=1)&$filter=Labors/any(o: o/Id eq 2)

**Comment by robinmaple** [comment] 2017-04-18 21:01
![image](https://cloud.githubusercontent.com/assets/7815640/25152899/d634657c-2447-11e7-98fe-09dcc6bff272.png)

**Comment by mikepizzo** [comment] 2017-05-30 21:49
Common requests (see, e.g., issue #400). Is this not fixed by PR #569?

**Comment by mikepizzo** [comment] 2017-05-30 21:57
Closing as dupe of #194. Please re-open if this issue appears distinct.

**Closed by mikepizzo** 2017-05-30 21:57 UTC
Labels: feature, P2
