### ISSUE TITLE
Problem when generating OData nextlink with a function parameter alias

### ISSUE THREAD

**Issue by rajni291** [OData/WebApi#2493] opened 2021-05-13 11:56 UTC
*Short summary (3-5 sentences) describing the issue.*

There is a problem when using Odata Web API with function parameter alias. 

Odata Original Request:
https://localhost:44374/odata/v3/HealthCare/Changes(startDate=@startDate)?@startDate=2020-06-06T14:03:00.6753255Z

OdataNextLink is generated as below:-
"@odata.nextLink":"https://localhost:44374/odata/v3/HealthCare/Changes(startDate=@startDate)?%40startdate=2020-06-06T14%3A03%3A00.6753255Z&$skip=1000"
The nextlink that is generated has lowercased the **startDate** in query (after ?). 

### Expected result
NextLink should maintain case sensitivity of any user defined parameter aliases.

### Actual result
NextLink is lower casing any user defined parameter aliases.

### Additional detail

In Class GetNextPageHelper, all query parameter keys are converted to lowercase. Can this be skipped if the key starts with '@'
signifying parameter alias.

**Comment by marabooy** [comment] 2021-05-19 09:12
Hi @rajni291, This does appear to be a bug which was intended to normalize the query options from OData so they are compared in a case insensitive manner. A good fix for this would be to only change the OData query options to lowercase and leave everything else in the same case. Would you be interested in contributing to a fix for this? If so do let me know if you need any help.

**Comment by rajni291** [comment] 2021-06-02 10:40
Hi @marabooy , I've created PR for the same, Could you look into that.
https://github.com/OData/WebApi/pull/2501

**Closed** 2022-11-09 08:36 UTC
Labels: bug, P3
