### ISSUE TITLE
NET 3.0 and Roadmap?

### ISSUE THREAD

**Issue by NetTecture** [OData/WebApi#1810] opened 2019-05-19 19:51 UTC
This project is getting awfully dead by now. At the same time, between problems with Ef Core 2.2 (that just has ridiculous amount of errors around executing complex sql, like... count) and .NET 3 and the given total incompatibility that seems to make it totally unable to run Odata Webapi on .NET 3.0 - what is the roadmap?

I understand that you have a policy of showing little progress and never communicating any meaningfull roadmap, which is a feature that really separates you from all the other MS teams, i.e. dotnetcore which just released the 5th preview of the SDK 3.0, and you really are unique in this non communication approach.

But as a user who starts actually having to have to plan some sort of project, I find a Milestone for 7.2 that seems to have no progress whatsoever and is 2 about 2 months overdue seriously bad for my customers plannings. I also understand the reason of running in circles and not publishing, but then given the ridiculous bad SQL that is partially generated by Ef Core 2.2 - and the fact that 3.0 is the version this is going to be fixed, supposedly - there is only ONE - and seriously only ONE - way one can sensibly move forward, and that is moving over to 3.0 as soon as possible.

#1748 i.e. has a post 9 days ago which indicates that it is still not even decided whether or not to go with endpoint based routing. Are you considering that your code may become amazingly valuable as antique at some point? Because otherwise there is zero reason not to go to endpoint based routing given the asp.net team has declared standards. I understand it must look bad to throw away all this code.

But the current alternative is to stay on dotnet core 2.2 - and the broken efcore 2.2 sql generation. You know how that one looks? We pull all data into memory in most cases because whole subsytems are otherwise totally broken (global queries i.e. - if a 1:1 relationship points to a filtered object the result is an exception in efcore -> unusable).

**Comment by robertmclaws** [comment] 2019-05-20 02:28
This post comes across as extremely rude. If that was the intention, fine... but there is nothing to be gained here with your wrongheaded and incorrect assertions. The EF query problem is NOT OData's fault,  I understand this might be an emotional issue for you, but you should step back and re-evaluate your architectural decisions. You keep trying to push forward... but there are more stable .NET + OData + EF platform choices available to you if you look to ASP.NET Classic. Microsoft said a LONG time ago that EF Core was going to have fewer features and be less stable than EF 6.X. If you needed stability, you should not have gone with EF Core.

**Comment by weitzhandler** [comment] 2019-09-27 01:24
I agree to the necessity, not to the way it's requested.
[Here](https://github.com/OData/WebApi/issues/1748#issuecomment-535579249)'s a comment that points to a potential direction we'd want to take in implementing the routes to make OData work in .NET Core 3 (by @KanishManuja-MS).

**Comment by weitzhandler** [comment] 2019-09-27 01:27
Looks like this issue is a duplicate of this one, that was opened earlier: https://github.com/OData/WebApi/issues/1748. Might be a good idea to keep the discussion in one place.

**Comment by mikepizzo** [comment] 2019-10-03 15:09
See longer discussion in #1748. Closing this thread to consolidate discussion.

**Closed by mikepizzo** 2019-10-03 15:09 UTC

**Comment by weitzhandler** [comment] 2019-10-03 15:30
Maybe a good idea to rename the other one to just ".NET Core 3.0", the current title is a bit out of date and deceiving.
