### ISSUE TITLE
Latest Microsoft.AspNet.OData (7.0.0-Nightly201805221243) breaks RESTIER

### ISSUE THREAD

**Issue by cilerler** [OData/WebApi#1444] opened 2018-05-23 13:03 UTC
reference https://github.com/OData/WebApi/issues/1059
cc @xuzhg 

I just updated [RESTIER](https://github.com/OData/RESTier) with latest nightly build **7.0.0-Nightly201805221243** _(and all I had to do was changing the all System.Web.OData to Microsoft.AspNet.OData)_ and started to receive error below.

```
HTTP/1.1 500 Internal Server Error
Content-Length: 2774
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
Date: Wed, 23 May 2018 12:46:48 GMT

{
  "message": "An error has occurred.",
  "exceptionMessage": "The object has not yet been initialized. Ensure that HttpConfiguration.EnsureInitialized() is called in the application's startup code after all other initialization code.",
  "exceptionType": "System.InvalidOperationException",
  "stackTrace": "at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.get_AttributeMappings()
                 at Microsoft.AspNet.OData.Routing.Conventions.AttributeRoutingConvention.SelectController(ODataPath odataPath, HttpRequestMessage request)
                 at Microsoft.AspNet.OData.Routing.ODataPathRouteConstraint.SelectControllerName(ODataPath path, HttpRequestMessage request)
                 at Microsoft.AspNet.OData.Routing.ODataPathRouteConstraint.Match(HttpRequestMessage request, IHttpRoute route, String parameterName, IDictionary`2 values, HttpRouteDirection routeDirection)
                 at System.Web.Http.Routing.HttpRoute.ProcessConstraint(HttpRequestMessage request, Object constraint, String parameterName, HttpRouteValueDictionary values, HttpRouteDirection routeDirection)
                 at System.Web.Http.Routing.HttpRoute.ProcessConstraints(HttpRequestMessage request, HttpRouteValueDictionary values, HttpRouteDirection routeDirection)
                 at System.Web.Http.Routing.HttpRoute.GetRouteData(String virtualPathRoot, HttpRequestMessage request)
                 at System.Web.Http.HttpRouteCollection.GetRouteData(HttpRequestMessage request)
                 at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                 at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                 at Microsoft.AspNet.OData.ETagMessageHandler.<SendAsync>d__0.MoveNext()
                   
                   --- End of stack trace from previous location where exception was thrown ---
                   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
                     
                     --- End of stack trace from previous location where exception was thrown ---
                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                     at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()

                       --- End of stack trace from previous location where exception was thrown ---
                       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                       at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"
}
```

**Comment by xuzhg** [comment] 2018-05-23 22:00
@cilerler Thanks for trying our new version nightly build. 

For your problem, I took some time to update the Restier project and added one sample project to test the nightly package. It seems it can work at my side and most of Restier test cases also can work based on the nightly package.

![image](https://user-images.githubusercontent.com/9426627/40453362-d254f542-5e99-11e8-9873-b995ff3a7c48.png)


Would you please take a look my commit at [here](https://github.com/xuzhg/RESTier/commit/95740f498fb5264f11449332ace9beaf308ae919)
 and compare with yours to figure out what's the difference? 

Please let us know any problem. Besides, I'd love to dig more if you can provide a repro for me to track on it. 

Thanks.

**Comment by cilerler** [comment] 2018-05-24 00:41
So far the only difference I see between your updates and mine is https://github.com/xuzhg/RESTier/blob/UpdateToWebAPIOData7x/src/Microsoft.Restier.Publishers.OData/Routing/HttpConfigurationExtensions.cs#L30 Mine is `Microsoft.AspNet.*` where your's is still `System.Web.*`

Even I believe you missed that, I tried to use it the way you provided and it thrown the same error.

I will create a sample repo that reproduces the issue and will post here...

**Comment by xuzhg** [comment] 2018-05-24 17:11
@cilerler 

I can't find any place referencing to this field: 
`private const string RootContainerKey = "System.Web.OData.RootContainerMappingsKey";`

I am wondering that you used "Find and Replace All" functionality to replace all "System.Web.OData" to "Microsoft.AspNet.OData". 😆 .

I removed this field (see https://github.com/xuzhg/RESTier/commit/99742065fe6a4da9a8e02b02dfb68224f1201802) and it gives me the same result. 

So, I can't wait to use your sample repro to dig more. Please let me know any help from our side. Thanks.

**Comment by cilerler** [comment] 2018-05-24 17:25
😆 well I tested yours and it works fine.  However mine is using almost every single feature exist in RESTier.  Trying to cut off all the non related parts so I can isolate the exact location.  

Also I realized that your example is not based on DI2 by the way ;-) just saying... 😂

**Comment by xuzhg** [comment] 2018-05-24 18:55
@cilerler 

Ok. Now I know the problem. 

The problem is that DI version 2.0 has a breaking change for the `BuildServiceProvider` extension method for `IServiceCollection`.  See issue at: https://github.com/aspnet/DependencyInjection/issues/550

Web API OData has a workaround and I merged into Restier, now it can work with DI2 at my side.

See at: https://github.com/xuzhg/RESTier/commit/e714052085a554bf1e06cdd702636b2a40f965c4

Please let me know any other problems.

**Comment by cilerler** [comment] 2018-05-24 22:09
I added `httpConfiguration.EnsureInitialized();` at the end of the configuration and then I did be able to see what is causing the issue.  Actual reason was `[ODataRoute("ImportQueues({key})/organization/$ref")]` part which I commented it out.  _(I can figure out why it is not happy with it since I have an actual error message)_

When I comment that out, I started to receive error message below.

```csharp
{
    "error": {
        "code": "",
        "message": "An error has occurred.",
        "innererror": {
            "message": "No model was specified in the ODataMessageWriterSettings; a model has to be provided in the ODataMessageWriterSettings in order to write a metadata document.",
            "type": "Microsoft.OData.ODataException",
            "stacktrace": " at Microsoft.OData.ODataMessageWriter.VerifyCanWriteMetadataDocument()
                            at Microsoft.OData.ODataMessageWriter.WriteMetadataDocument()
                            at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
                            at Microsoft.AspNet.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)
                            --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__24.MoveNext()
                            --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__49.MoveNext()
                            --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at System.Web.Http.Owin.HttpMessageHandlerAdapter.<BufferResponseContentAsync>d__13.MoveNext()
                          "
        }
    }
}
```

However, I tried to test against entity and it worked, so I realized that issue is related to retrieving `/?$metadata` part.

Last, I didn't upgrade it to DI2 until now.  Since entity portion is working, I decided to upgrade it and it did work without any problem.  So issue is now narrowed to `$metadata`

**Comment by xuzhg** [comment] 2018-05-24 22:13
@cilerler A working repro (as simple as possible) can help us a lot. Would you please create one?

**Comment by cilerler** [comment] 2018-05-25 00:03
@xuzhg I'm on it...  I will get back to you...

**Comment by cilerler** [comment] 2018-05-25 02:16
Took while but pin-pointed the issue.

Just change the line [here](https://github.com/xuzhg/RESTier/blob/UpdateToWebAPIOData7x/test/MyWebApplication/Global.asax.cs#L14) in your sample project with code below

```csharp
    using (var httpConfiguration = GlobalConfiguration.Configuration)
    {
        //httpConfiguration.EnableDependencyInjection();

        WebApiConfig.Register(httpConfiguration);
        httpConfiguration.EnsureInitialized();
    }
```

it will work fine.

Then un-comment the commented line and you will get the error.

**Comment by AlanWong-MS** [comment] 2018-05-30 20:42
@cilerler, based on the conversation, we're going to close this issue and please feel free to open this one against RESTier. Thanks.

**Closed by AlanWong-MS** 2018-05-30 20:42 UTC
Labels: P1
