### ISSUE TITLE
GroupBy stop working at version 6.1.0 of Microsoft.AspNet.OData

### ISSUE THREAD

**Issue by jvitor83** [OData/WebApi#1078] opened 2017-09-16 05:24 UTC
At version 6.0.0 of Microsoft.AspNet.OData it works. After upgrade to 6.1.0 GroupBy stop working!

### Assemblies affected

https://www.nuget.org/packages/Microsoft.AspNet.OData/6.1.0

### Reproduce steps

Make a GroupBy request to a OData endpoint.

- Clone this repo -> https://github.com/jvitor83/OData.Sample
- Run the solution
- Make a request to `http://localhost:60469/People?$apply=groupby((Id))`

### Expected result

The request return.

At the Sample: `[
    {
        "Id": 1
    },
    {
        "Id": 2
    }
]`

### Actual result

The following error at response:
```
{
    "Message": "Ocorreu um erro.",
    "ExceptionMessage": "O tipo 'ObjectContent`1' não pôde serializar o corpo da resposta para o tipo de conteúdo 'application/json; charset=utf-8'.",
    "ExceptionType": "System.InvalidOperationException",
    "StackTrace": null,
    "InnerException": {
        "Message": "Ocorreu um erro.",
        "ExceptionMessage": "Error getting value from 'NestedValue' on 'System.Web.OData.Query.Expressions.AggregationPropertyContainer+LastInChain'.",
        "ExceptionType": "Newtonsoft.Json.JsonSerializationException",
        "StackTrace": "   em Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)\r\n   em Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)\r\n   em Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   em Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   em Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   em Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   em Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   em Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   em Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)\r\n   em Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)\r\n   em System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\r\n   em System.Net.Http.Formatting.JsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\r\n   em System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content)\r\n   em System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()",
        "InnerException": {
            "Message": "Ocorreu um erro.",
            "ExceptionMessage": "Não é possível converter um objeto do tipo 'System.Int32' no tipo 'System.Web.OData.Query.Expressions.GroupByWrapper'.",
            "ExceptionType": "System.InvalidCastException",
            "StackTrace": "   em GetNestedValue(Object )\r\n   em Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)"
        }
    }
}
```

### Additional detail

At the sample (https://github.com/jvitor83/OData.Sample) if you downgrade to version 6.0.0 of Microsoft.AspNet.OData the request _(at reproduce steps)_ works.

**Comment by mtroth-microsoft** [comment] 2017-09-16 17:46
I wasn't able to reproduce this with my own project, using NORTHWND.

**Comment by jvitor83** [comment] 2017-09-16 20:11
@mtroth-microsoft  can you put the solution at some repo, so i can see the diference?

In my sample only works with version 6.0.0

**Comment by mtroth-microsoft** [comment] 2017-09-16 21:09
The code isn't shared anywhere but it is a vanilla use of entity framework queryable. i'll look at a Linq based sample like yours Monday. does your issue repo when using the 6.1.0-beta of webapi?

**Comment by jvitor83** [comment] 2017-09-16 21:30
Yes, it happend at 6.1.0-beta too.

**Comment by AlanWong-MS** [comment] 2017-09-21 23:15
@jvitor83, I wasn't able to repro, but I am taking a look at past commits to see if I find anything of interest. In the meantime, please provide any additional findings that you may have regarding this case.

**Comment by jvitor83** [comment] 2017-09-22 04:23
I made some changes at the repo of sample to get a little deeper on the issue.
> The PeopleController has 2 implementations, one with `ApiController` and another with `ODataController`.

What i learn is:
- If the Controller inherit from `ODataController`, the `Get` method return `IQueryable<Person>` with `[EnableQuery]` attribute and don't have the `ODataQueryOptions<Data.Person> options` as parameter to apply, it works.
- If the Controller inherit from `ApiController`, the `Get` method return `IQueryable` and have `ODataQueryOptions<Data.Person> options` as parameter to apply at the IQueryable, it breaks (but only at version `6.1.0`).

If you get my sample and put the breakpoint at https://github.com/jvitor83/OData.Sample/blob/master/OData.Sample/Controllers/PeopleController.cs#L38 you will see that the `Type` after applied and executed the IQueryable is of `System.Web.OData.Query.Expressions.AggregationWrapper`, and my guess is that this type is not supported.

The point is:
- At version 6.0.0, the `Type` at https://github.com/jvitor83/OData.Sample/blob/master/OData.Sample/Controllers/PeopleController.cs#L38 is `System.Web.OData.Query.Expressions.DynamicTypeWrapper` and it WORK
- At version 6.1.0 the `Type` at https://github.com/jvitor83/OData.Sample/blob/master/OData.Sample/Controllers/PeopleController.cs#L38 is `System.Web.OData.Query.Expressions.AggregationWrapper` and ir BREAK

**_So, the Type of the Model after applied by the `ODataQueryOptions` (with a groupby clause) is the guilty here._**

**Comment by biaol-odata** [comment] 2017-09-29 23:37
@jvitor83: since @kosinsky has #1090 opened to fix this issue. I am going to close this one for now.

**Comment by biaol-odata** [comment] 2017-09-29 23:41
Actually, let's keep this issue opened until the @kosinsky 's PR is merged.

**Comment by biaol-odata** [comment] 2017-10-02 21:30
https://github.com/OData/WebApi/pull/1090 has been merged.
Closing.

**Closed by biaol-odata** 2017-10-02 21:30 UTC
Labels: P1, regression
