### ISSUE TITLE
7.5.16 Wrong referenced version Newtonsoft.Json 13.0.0.0

### ISSUE THREAD

**Issue by csharp4fun2** [OData/WebApi#2701] opened 2022-08-18 10:34 UTC
Hi, 
I changed to OData version 7.5.16 and got problems because it can't find Newtonsoft.Json 13.0.0.0. 
I checked out the changes in code and found that the Newtonsoft.Json 13.0.0.0 is referenced but with a HintPath to 13.0.0.1. 
13.0.0.0 isn't public available, 13.0.0.1 is. So it will compile if you have locally 13.0.0.1 lying around but not if you don't. 

I marked here the line I think which is wrong:
[Diff for 7.5.16](https://github.com/OData/WebApi/compare/7.5.15...7.5.16#diff-995a2ba548af189a362723f0fa7c69d21342b5537099bab86bc4cc2fda339439R103)

Best regards,
Gerald

**Comment by xuzhg** [comment] 2022-08-18 18:02
@habbes The csproj changes were updated automatically when we updated the newtonsoft.json. It's not manually updated.

For the potential root cause, i think, is related to this line. https://github.com/OData/WebApi/blob/master/tools/WebStack.versions.settings.targets#L19.  

As a workaround, @csharp4fun2 does it work if you update the newtonsoft.json package version to 13.0.0.1 or above manually?

**Comment by robertmclaws** [comment] 2022-08-18 18:07
That Newtonsoft version needs to be a range. It should be [13.0.1, 14.0)

**Comment by xuzhg** [comment] 2022-08-18 20:37
> That Newtonsoft version needs to be a range. It should be [13.0.1, 14.0)

It could be a problem for customers to udpate (manually) to new version bigger than 14.0.

**Comment by robertmclaws** [comment] 2022-08-18 21:35
Right, that means it's working as intended. As of this moment, the OData team cannot guarantee there will not be breaking changes in JSON.NET in v14. NOT specifying a range locks them into using 13.0.1 for forever, and that's not what you want.

 You want to guarantee they can use v13 releases, and when you know the codebase supports v14, you extend the range and release an updated ODL package that provides expanded support.

**Comment by csharp4fun2** [comment] 2022-08-22 06:50
> @habbes The csproj changes were updated automatically when we updated the newtonsoft.json. It's not manually updated.
> 
> For the potential root cause, i think, is related to this line. https://github.com/OData/WebApi/blob/master/tools/WebStack.versions.settings.targets#L19.
> 
> As a workaround, @csharp4fun2 does it work if you update the newtonsoft.json package version to 13.0.0.1 or above manually?

Let's say: it is working if you have the 13.0.0.1 somewhere referenced in you project because then the hint path does work.

**Comment by csharp4fun2** [comment] 2022-08-22 06:52
> That Newtonsoft version needs to be a range. It should be [13.0.1, 14.0)

In my opinion it is fine if just 13.0.1 is referenced. Not a fan on doing ranges and bet that it will work with future versions as well. Better updating from time to time to latest versions and for sure if critical patches are coming out updating as fast as possible.

**Comment by robertmclaws** [comment] 2022-08-22 14:05
Ranges make sure the end user can reference whatever version they want, vs locking to a specific version and potentially creating problems for the end-user if the want or need a newer version. If you're having a problem with ranges, that means someone is doing SemVer wrong.

**Comment by robertmclaws** [comment] 2022-08-23 05:11
I believe this issue has been fixed in 7.5.17. @csharp4fun2 can you please confirm?

**Closed** 2022-08-26 08:53 UTC
Labels: bug, regression, P1, fixed
