### ISSUE TITLE
ODataConventionModelBuilder.GetEdmModel throws StackOverflowException For Recursive Complex Types

### ISSUE THREAD

**Issue by tompetko** [OData/WebApi#1248] opened 2018-02-22 15:41 UTC
Building EDM Model for model, that contains recursion member, throws **StackOverflowException**.

### Assemblies affected

OData WebApi lib 6.1.0

### Reproduce steps

Model definitions:
```
public sealed class ReceiptItemPLU
{
    public string Name { get; set; }
    public ReceiptItem[] Receipt { get; set; }
}

public sealed class ReceiptItem
{
    public decimal Quantity { get; set; }
    public ReceiptItemPLU Plu { get; set; }
}

public sealed class PLU
{
    [Key]
    public int Id { get; set; }
    public string Name { get; set; }
    public ReceiptItem[] Receipt { get; set; }
}
```

EDM Model building:
```
var builder = new ODataConventionModelBuilder();
builder.EntitySet<PLU>("Plu");
var edmModel = builder.GetEdmModel();
```

### Expected result

I was trying to bypass direct recursion constraint by creating new type, so I'm not quite sure of the expected result, but I assume it should throws proper Exception like this one:

`'The complex type '{TypeName}' has a reference to itself through the property '{PropertyName}'. A recursive loop of complex types is not allowed.`.

But it would be nice to support this :)

### Actual result

*StackOverflowException*

**Comment by Compufreak345** [comment] 2018-03-21 15:57
Is there any known workaround for this issue, like a maximum deepness that can be set?

I am trying to create EDMModel for "database first"-generated EFCore-Models and I am not sure if it's possible to solve the circular references that are in the generated code.

**Comment by brjohnstmsft** [comment] 2018-04-25 01:31
This issue is a problem for me too, but in my case I get a more sensible error than `StackOverflowException`:

```
[ArgumentException: The complex type 'Address' has a reference to itself through the property 'ForwardingAddresses'. A recursive loop of complex types is not allowed.
Parameter name: propertyInfo]
   System.Web.OData.Builder.StructuralTypeConfiguration.AddCollectionProperty(PropertyInfo propertyInfo) +686
   System.Web.OData.Builder.ODataConventionModelBuilder.MapStructuralProperty(StructuralTypeConfiguration type, PropertyInfo property, PropertyKind propertyKind, Boolean isCollection) +415
   System.Web.OData.Builder.ODataConventionModelBuilder.MapStructuralType(StructuralTypeConfiguration structuralType) +168
   System.Web.OData.Builder.ODataConventionModelBuilder.MapType(StructuralTypeConfiguration edmType) +46
   System.Web.OData.Builder.ODataConventionModelBuilder.AddComplexType(Type type) +31
   System.Web.OData.Builder.ODataConventionModelBuilder.ReconfigureEntityTypesAsComplexType(EntityTypeConfiguration[] misconfiguredEntityTypes) +915
   System.Web.OData.Builder.ODataConventionModelBuilder.RediscoverComplexTypes() +142
   System.Web.OData.Builder.ODataConventionModelBuilder.GetEdmModel() +124
   NewODataTestDrive.WebApiConfig.Register(HttpConfiguration config) in C:\Users\brjohnst\Documents\Visual Studio 2015\Projects\NewODataTestDrive\App_Start\WebApiConfig.cs:15
   System.Web.Http.GlobalConfiguration.Configure(Action`1 configurationCallback) +27
   NewODataTestDrive.WebApiApplication.Application_Start() in C:\Users\brjohnst\Documents\Visual Studio 2015\Projects\NewODataTestDrive\Global.asax.cs:14

[HttpException (0x80004005): The complex type 'Address' has a reference to itself through the property 'ForwardingAddresses'. A recursive loop of complex types is not allowed.
Parameter name: propertyInfo]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +10062145
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +173
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): The complex type 'Address' has a reference to itself through the property 'ForwardingAddresses'. A recursive loop of complex types is not allowed.
Parameter name: propertyInfo]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +10043436
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +95
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254
```

@xuzhg Is there a timeframe for implementing this feature?

**Comment by brjohnstmsft** [comment] 2018-04-25 01:35
Actually, this might be a regression, as this was supposed to be fixed in Web API OData 6.1: https://github.com/OData/WebApi/issues/930

@robward-ms I can repro this in 6.1. Did the fix not take...?

**Comment by brjohnstmsft** [comment] 2018-04-25 21:15
I'm going to poke around and see how much work it is to fix this.

**Comment by Compufreak345** [comment] 2018-04-30 09:08
For me the issue seems to be resolved, I get no exceptions anymore during the generation of my model on the nightly builds for netcore.

**Comment by brjohnstmsft** [comment] 2018-05-11 02:04
@Compufreak345 Would you mind sharing your model? I'm still able to repro this issue in three different scenarios for both version 6 and the latest nightly of version 7.0.0-Nightly201805101240, both running on .NET Framework 4.6.1.

**Comment by brjohnstmsft** [comment] 2018-05-11 05:59
I believe I've figured out why this issue seems to persist for some of us while others report that it's been resolved. It's because there are distinct types of recursive models, and the original bug and its fix only affect some of them. The overall scenario of supporting recursive data structures as complex types is definitely still broken.

Here are the four scenarios I tested:

**Scenario 1: Direct reference**

```
class A
{
    public A InnerA { get; set; }
}
```

**Scenario 2: Collection**

```
class A
{
    public List<A> As { get; set; }
}
```

**Scenario 3: Composition**

```
class A
{
    public B RelatedB { get; set; }
}

class B
{
    public A RelatedA { get; set; }
}
```

**Scenario 4: Inheritance**

```
abstract class A
{
}

class B : A
{
    public string SomeProperty { get; set; }
}

class C : A
{
    public List<A> As { get; set; }
}
```

The behavior appears to be different for some of these cases across different versions. Here is what I observed for the versions I tested with:

Scenario: | Direct | Collection | Composition | Inheritance
-- | -- | -- | -- | --
5.9.1 | ArgumentException | ArgumentException | Works | Works
6.0.0 | ArgumentException | ArgumentException | StackOverflowException | StackOverflowException
6.1.0 | ArgumentException | ArgumentException | StackOverflowException | Works
7.0.0-Nightly201805101240 | ArgumentException | ArgumentException | StackOverflowException | Works

Note that the exception message for ArgumentException is always "A recursive loop of complex types is not allowed".

The failures in the Direct and Collection scenarios make sense given that this code is still present: https://github.com/OData/WebApi/blob/c5893e23ef18774dbaac855fadbcc7f6f22f612e/src/Microsoft.AspNet.OData.Shared/Builder/StructuralTypeConfiguration.cs#L384
https://github.com/OData/WebApi/blob/c5893e23ef18774dbaac855fadbcc7f6f22f612e/src/Microsoft.AspNet.OData.Shared/Builder/StructuralTypeConfiguration.cs#L449

So it appears the fix is only for one narrow case (indirect recursion via inheritance) and fails to address the other cases.

Unfortunately the case that matters most to me is the Collection scenario, and it remains broken (apparently on purpose). I'll consider inheritance as a workaround, but if that won't suffice, I'll continue to investigate the effort required to make all forms of recursive references allowable.

**Comment by Compufreak345** [comment] 2018-05-14 11:00
@brjohnstmsft Unfortunately I don't think I have the permission to publish my model here as it's from a customer project. I had a look at it but it isn't inheritance (as it's an auto-generated EFCore-model), I think it's a combination of collections, direct reference collections and compositions over multiple classes like this - I hope I modeled it right as our database model is a bit strange as it is a result of a migration from Sharepoint-Lists to a database 😕 : 

```csharp 
class A
{
    public B RelatedB { get; set; }
    public ICollection<C> RelatedCs {get;set;}
    public C RelatedC {get;set;}
    public ICollection<A> RelatedA {get;set;}
}

class B
{
    public ICollection<A> RelatedAs {get;set;}
    public ICollection<C> RelatedCs {get;set;}
}

class C {
    // Previously - IIRC - my issues got resolved by removing this line, now it seems to work fine.
    public B RelatedB {get;set;}
}
```

Regarding to your issues I am wondering why my code is working - maybe because of differences between the netcore-version I am using and the one you are using? I also have ForeignKey- and InverseProperty-annotations on my relationships, that might be another difference to your code.

**Comment by brjohnstmsft** [comment] 2018-05-14 16:40
@Compufreak345 I should have mentioned above that none of my testing involves any navigation properties whatsoever (because we don't use them in my scenario). Are any of the recursive relationships in your model above *not* modeled as navigation properties?

**Comment by Compufreak345** [comment] 2018-05-15 15:42
@brjohnstmsft Oh - no, all of my relationships are modeled as navigation properties.

**Comment by brjohnstmsft** [comment] 2018-06-02 00:07
I'm working on pinning tests for all the above cases now, and I learned something interesting about scenario 3 that I wanted to share for posterity. It appears that the `StackOverflowException` doesn't happen when adding the complex type to the model directly via the `.ComplexType<T>()` method. However, when using `.EntitySet<T>("name")` method, it does happen. Unfortunately calling `ComplexType` before `EntitySet` does not seem to be a viable workaround -- as soon as there is an entity type referencing the recursive complex type, `GetEdmModel` will throw `StackOverflowException`.

**Closed** 2018-06-11 04:05 UTC
Labels: feature
