### ISSUE TITLE
OData rises an exception when it expands twice the same property with different case

### ISSUE THREAD

**Issue by nmoreaud** [OData/WebApi#1836] opened 2019-06-22 16:02 UTC
If I ask twice to expand a subresource in the url with 2 different cases, an exception happens and the Rest API response is generated partialy.
This also happens if I try to expand a subresource that is expanded by default ([AutoExpand]) with an alternative case.

### Assemblies affected

Microsoft.AspNetCore.OData 7.1.0

### Reproduce steps

    https://localhost:44381/api/offers?$expand=Category,category
    https://localhost:44381/api/offers?$expand=categorY,category
    https://localhost:44381/api/offers?$expand=category + [AutoExpand] on Category field
    https://localhost:44381/api/offers?$expand=Category + EnableLowerCamelCase() + [AutoExpand] on Category field
    https://localhost:44381/api/offers?$expand=category,category => no error !

### Expected result

The subresource should be expanded without errors.

### Actual result

The response is truncated and an exception is triggered
`{"@odata.context":"https://localhost:44381/api/$metadata#Offers","value":[
`

Exception :

    offers_api> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
    offers_api>       An unhandled exception has occurred while executing the request.
    offers_api> System.ArgumentException: An item with the same key has already been added. Key: Microsoft.OData.Edm.EdmNavigationProperty
    offers_api>    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
    offers_api>    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
    offers_api>    at Microsoft.AspNet.OData.Formatter.Serialization.SelectExpandNode.BuildExpansions(SelectExpandClause selectExpandClause, HashSet`1 allNavigationProperties)
    offers_api>    at Microsoft.AspNet.OData.Formatter.Serialization.SelectExpandNode..ctor(SelectExpandClause selectExpandClause, IEdmStructuredType structuredType, IEdmModel model)
    offers_api>    at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateSelectExpandNode(ResourceContext resourceContext)
    offers_api>    at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
    offers_api>    at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
    offers_api>    at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
    offers_api>    at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)

**Comment by gathogojr** [comment] 2020-11-03 12:57
@nmoreaud Retested all 4 scenarios reported to be causing errors against Microsoft.AspNetCore.OData 7.5.1 and the issue is no longer reproducible. Issue most likely fixed in releases after 7.1.0.

**Closed by gathogojr** 2020-11-03 12:57 UTC
Labels: bug
